### ISSUE TITLE
Leaf Floor Coverings Issue

### ISSUE THREAD

**Issue by RockwoodZapper** [mc-jt9/ProjectVibrantJourneys#1]
When Leaf-Based floor coverings are next to any block, the surface that the covering is touching becomes see-through. This isn't game-breaking, however it's amazingly annoying when it's on an aesthetics mod.

**Comment by mc-jt9** [comment]
This is a mod-breaking bug. I'll look into it right now.

**Comment by mc-jt9** [comment]
Fixed in v1.0.1. It was an issue with the isOpaqueCube(IBlockState state) method.
