### ISSUE TITLE
Cannot disable biomes in config--potential TerraForged incompatibility?

### ISSUE THREAD

**Issue by dirt-worm** [mc-jt9/ProjectVibrantJourneys#100]
I keep setting the weight of aspen grove and crimson thicket biomes to 0, but they still continue to generate. The only other world generation mod that I have that affects biome generation is TerraForged. Is this a compatibility issue? What can I do to prevent these biomes from spawning?

**Comment by OrderedChaos-Dev** [comment]
The config relies on the vanilla world gen system to handle biome weights, so it might be a TerraForged thing since they use their own world generator. I'll see if I can add in a check in my biome stuff to prevent that from happening.

**Comment by OrderedChaos-Dev** [comment]
Turns out I've already implemented a check to stop that. It's probably TerraForged's world generation
