### ISSUE TITLE
Frogs

### ISSUE THREAD

**Issue by heidefinnischen** [mc-jt9/ProjectVibrantJourneys#102]
I think small frogs would be quite fitting for this mod. little basic frogs like in these pictures. 
![2018-01-02_10](https://user-images.githubusercontent.com/58484745/80894564-4d8cfa80-8cdc-11ea-9e0b-4bbbd49fc482.png)
![2018-01-02_10](https://user-images.githubusercontent.com/58484745/80894568-5b428000-8cdc-11ea-8b7d-1160c4386ab4.png)

**Comment by OrderedChaos-Dev** [comment]
I like that idea! Did you make those models yourself? Those are cute frogs
