### ISSUE TITLE
New mobs and problems

### ISSUE THREAD

**Issue by HioshiTsuki** [mc-jt9/ProjectVibrantJourneys#103]
I think this mod needs some mobs
What about little crabs?They will spawn in beach biome and drop their meat
Piranhas-agressive mobs and they will spawn in rivers and swamps
Wither skeletons-archers,they will spawn in the Nether and attack us
Chipmunks will spawn in forests
And I saw 1 bug in generation,sometimes trees in mod spawn weird
![Inked2020-05-04_15 25 27_LI](https://user-images.githubusercontent.com/64776117/80952871-3a814400-8e1c-11ea-95dd-034fb9d45d71.jpg)
![Inked2020-05-04_15 26 14_LI](https://user-images.githubusercontent.com/64776117/80952982-74524a80-8e1c-11ea-8fe1-99f95a608d49.jpg)

**Comment by OrderedChaos-Dev** [comment]
I had some of those mob suggestions in mind before, not sure if I'll have those in though. There are other mobs being planned as well. Not sure how I didn't catch that palm tree issue, I'll have it fixed

**Comment by HioshiTsuki** [comment]
Cool!
