### ISSUE TITLE
[Suggestion] Flower lilypad

### ISSUE THREAD

**Issue by Matthysse** [mc-jt9/ProjectVibrantJourneys#104]
Hello!

I just love your mod, it brings so much athmosphere to the game. There was the Lion King mod in Minecraft 1.4.7 which added the flowers water lilypads. I loved them but there is absolutely no mods which add these lily pads to the newer versions of the game. Imagine having those water lily pads in generated biomes, it would look so nice!
Here is an example (it would come in different colour variations) :
![$_57](https://user-images.githubusercontent.com/32510957/81571474-4a5fd180-93a2-11ea-83f6-067626d2af0f.jpg)

**Comment by OrderedChaos-Dev** [comment]
I like this idea, will add it to list of things to do

**Comment by OrderedChaos-Dev** [comment]
https://www.curseforge.com/minecraft/mc-mods/bayou-blues
They do it better hehe
