### ISSUE TITLE
Groundcover breaks chests and makes them disappear

### ISSUE THREAD

**Issue by SissyTrashQueen** [mc-jt9/ProjectVibrantJourneys#109]
Minecraft: 1.15.2
Forge: 31.2.0
projectvibrantjourneys-1.15.2-2.0.2

Right-clicking with flint/nugget in the main hand, on the upper face of the block that's directly below a chest, will break the chest, its content will drop, but the chest itself won't because it was yeeted to the Void.
[Video showing this](https://imgur.com/a/jrh8S7y)

Nuggets and flint can replace anything, they can even replace mutually if you try hard enough. I don't think vanilla flint/nuggets should have the same behaviour as groundcover flint/nuggets

**Comment by Quadruplay** [comment]
It also happens with every block that doesn't take up the full cube

**Comment by OrderedChaos-Dev** [comment]
Uh oops, I added a fix for it but forgot to release it. I'll push the fix out tomorrow.

**Comment by OrderedChaos-Dev** [comment]
Uploaded to CurseForge, should be approved soon.
