### ISSUE TITLE
[Crash][1.12.2-1.1.2] Server crash on startup

### ISSUE THREAD

**Issue by Marlax0** [mc-jt9/ProjectVibrantJourneys#11]
This mod is causing a dedicated server crash on startup.
Same results with a full mod list, and just with this mod.

Crash log seems to imply it's trying to run client-side only code on the server.
If I missed somewhere that your mod doesn't support SMP, then I apologize.

Latest version of Java (1.8.0_181) and Forge-14.23.4.2751.

Crash log:
https://pastebin.com/NdkP5NKN

Edit: Also, here's a log from the server with just this mod:
https://pastebin.com/c5KmRLHa

**Comment by mc-jt9** [comment]
fixed in v 1.1.3
