### ISSUE TITLE
Redwood Trees shaped like Jungle Trees (1.15)

### ISSUE THREAD

**Issue by merlerm** [mc-jt9/ProjectVibrantJourneys#110]
I've been playing around with PVJ and BOP on 1.15 recently, and I couldn't help but notice PVJ Redwood spawns with the canopy shaped like a vanilla Jungle Tree, which looks incredibly off, so I can only assume it's a bug.
https://imgur.com/a/W0iaYc1 (screenshot for reference, also happens in PVJ redwood biomes). 

The issue seems to persist even with just PVJ installed, as seen in https://imgur.com/a/Sx5NdCk

I have PVJ 2.0.3 installed.

**Comment by OrderedChaos-Dev** [comment]
That is intentional, meant to mimic another type of redwood. It really just generates a circle of leaves at random points + the top of the tree.
