### ISSUE TITLE
Sea Oats placeable blocks are hardcoded

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [mc-jt9/ProjectVibrantJourneys#111]
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/e74eea9e8fe96631aea3097f1f90b88e2338135b/src/main/java/projectvibrantjourneys/common/blocks/SeaOatsBlock.java#L25

Preferably, you'd either use `instanceof` checks here to make sure it can be planted on other blocks that extend `DirtBlock` (for instance, BoP dirt types) or make a tag (á la vanilla `#minecraft:bamboo_plantable_on`) to make it configurable through datapacks which blocks plants should be able to be placed on

**Comment by OrderedChaos-Dev** [comment]
Ah yes, sometimes I just type out my thoughts when adding behavior to blocks and forget to actually account for things like this. I'll take a look at the pr and put together a patch

**Comment by OrderedChaos-Dev** [comment]
I saw the pr, I'm going to go for checking the block's material instead of tags to keep it small.
