### ISSUE TITLE
Biome generation config broken when loading exactly 50 or more forge mods. [1.15.2]

### ISSUE THREAD

**Issue by BigBullmoose** [mc-jt9/ProjectVibrantJourneys#114]
Had been using this mod for a while with 37 mods loaded, had my config set how i liked it for the biome rates. Added some new mods to my game, up to around 54. Made a new world with the same seed id been playing on to make sure the mods played nice, and specifically these biomes were generated completely differently, while vanilla biomes stayed in their same spots. After LOTS of testing, i realized that none of the mods i got specifically were incompatible or changing the world gen at all. I added every new mod 1 by 1 and tested that worlds gen each time to find the culprit, none of these mods even affected world gen at all, turns out doesn't matter what mods are installed, as soon as i hit 50 mods the issue happens. For some reason, when i add the 50th mod (49 in the actual mod folder, forge counts 50 in game), either my configs don't load or the generation just changes for some reason. Very bizarre, drove me nuts to figure out, have no idea why or how this could be happening.

**Comment by BigBullmoose** [comment]
![2020-08-02_04 42 53](https://user-images.githubusercontent.com/65634364/89124095-21bf1380-d489-11ea-8078-e020e762da8c.png)
 This is the spawn that i want, near these verdant sands while under 50 mods
![2020-08-02_04 43 18](https://user-images.githubusercontent.com/65634364/89124124-58952980-d489-11ea-9490-c4419add7ccc.png)
 This is the spawn i get when loading over 50 mods, similar area but the spawn location is moved and biomes aren't the same 
 location

This issue was 100% reproductable. I then uninstalled PVJ and loaded the seed with both under 50 mods and over 50 mods, and the spawn was the exact same.

**Comment by BigBullmoose** [comment]
also side note, bears never spawned naturally for me anywhere, but thats less important

**Comment by OrderedChaos-Dev** [comment]
Sorry for the late reply. I don't really know what to tell you lol, there's nothing different about this and other biome mods, and I have no idea why it's 50. 
The bears are also a rare mob.
