### ISSUE TITLE
[1.15.2][Multiplayer] Crash on a world load

### ISSUE THREAD

**Issue by dreckz** [mc-jt9/ProjectVibrantJourneys#117]
PVJ Version: 2.0.3
Forge: 31.2.35

On a world load, the server crashes and outputs this crash log:
[crash-2020-08-08_02.37.36-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/5044824/crash-2020-08-08_02.37.36-server.txt)

**Comment by OrderedChaos-Dev** [comment]
Might've been from being built on an outdated Forge version. Can't reproduce this error on after building on 1.15.2's recommended 31.2.0.

Will put out that updated build soon
