### ISSUE TITLE
Grimoire of Gaia and Vanilla mobs not spawning

### ISSUE THREAD

**Issue by borianudziarz** [mc-jt9/ProjectVibrantJourneys#119]
Hi!
I've made a pack with your mod and with Animania, Grimore of Gaia and Biomes'O'Plenty and I found out, that mobs from this mods are not spawning on biomes and generally stuff from VJ. I double checked and it's only problem with VJ, because on other locations, even on BOP the problem doesn't exist. Vanilla mobs also are not spawning, but only in the caves.
Can it be because of that the mobs don't recognize this biomes as a places where they can spawn?
Also I see a big difference between amount of spawned mobs with VJ and without, on other locations (without is more mobs).
Do you have any idea whats the problem, if this is a problem with your mod, not with others :D
We really like this mod, because it is adding some life and spice to the world and you made an awesome work, but mobs don't want to corelate with it ;-;
We're gonna looking for the problem in other mods, but it would be nice if you would check this :3 

We tried putting only Animania, BoP, GoG and VJ together in a lot of different corelations and the problem is only when VJ is added :/ 
version 1.12.2

**Comment by OrderedChaos-Dev** [comment]
Hey, sorry for the REALLY late reply. I'm not sure what's causing that since I had added integrating with BoP in 1.12. I am not working on that version anymore though, due to time constraints.
