### ISSUE TITLE
[1.12.2-1.1.4] Cascading worldgen lag (Forge-14.23.4.2756)

### ISSUE THREAD

**Issue by Marlax0** [mc-jt9/ProjectVibrantJourneys#12]
Getting a decent amount of these warnings on a test server with no other mods, but it is playable.

In a large modpack, the cascading worldgen is so insane that the server is forced to shut down after about 5 minutes because the tick time gets too high. I'm never able to join the server.
Also happening in singleplayer.

1.1.2 in singleplayer was working just fine in my large modpack.

Crash log when the Watchdog kills the server:
https://pastebin.com/uuceACLJ

**Comment by mc-jt9** [comment]
Looks like it's the new dungeons spilling out into neighboring chunks. I'll have them generate in the middle of a chunk.

**Comment by Marlax0** [comment]
I can confirm setting B:modifyDungeons to false removes the issue entirely.

**Comment by mc-jt9** [comment]
Tested on a server and got multiple cascading errors. Modified dungeon generation slightly in v1.1.5, generated 4 new worlds on a server and client and found 0 cascading world gen errors after the change.
