### ISSUE TITLE
Trees break blocks above

### ISSUE THREAD

**Issue by WenXin20** [mc-jt9/ProjectVibrantJourneys#120]
`Minecraft v1.15.2`
`Forge v31.2.45`
`PVJ v2.0.4`

When saplings are grown or when the world generates a tree, they can grow through any blocks placed directly above it, and the leaves will break any block, including bedrock.

**Comment by OrderedChaos-Dev** [comment]
This was a result of lazy programming, my bad. I'm moving forward with 1.16 though without any of the trees
