### ISSUE TITLE
Entity rendering slowdowns

### ISSUE THREAD

**Issue by CraftSpider** [mc-jt9/ProjectVibrantJourneys#123]
Game Version: 1.15
Mod Version: 2.0.4

The rendering of certain entities from this mod seems to be causing slowdown, vastly outweighing other entities during the gameRender tick. Disabling the entity spawning in all biomes + killing the remaining makes my game noticeably faster. I'm not super familiar with minecraft/forge programming, but my first guess is either the Snails/Starfish textures, which creates a new ResourceLocation each call unlike many of the other mobs?

**Comment by OrderedChaos-Dev** [comment]
I didn't notice an issue with that during development but it's probably poor optimization on my part. Either way, I stopped working on older versions which is why I was slow to reply, sorry.
