### ISSUE TITLE
Cant disabled dimensional generation through config (Running Pixelmon)

### ISSUE THREAD

**Issue by Phynn2** [mc-jt9/ProjectVibrantJourneys#124]
I'm trying to disable generation in dimension 72 (ultra space)

S:dimensionBlacklist=

I try inputing any dimension value (0, 1, -1, 72)

72 for example:

S:dimensionBlacklist=72

This disabled generation in all dimensions no matter what the value is
for more examples:

S:dimensionBlacklist=1
S:dimensionBlacklist=-1,1
S:dimensionBlacklist=0

I'm not sure why this is. I just want to disable it's generation in ultra space because it will cause a crash.

**Comment by OrderedChaos-Dev** [comment]
Sorry the dimension blacklist was poorly written and I've stopped development on older versions to work on the 1.16 one
