### ISSUE TITLE
Crash when clicking Create New World.

### ISSUE THREAD

**Issue by MagmaSlime123** [mc-jt9/ProjectVibrantJourneys#129]
Mods and other info are in these links.

https://pastebin.com/S41LSE5F
[latest.log](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6135686/latest.log)

**Comment by OrderedChaos-Dev** [comment]
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/ExceptionUtils

Huh, I'm pretty sure this library is included in vanilla but I guess not

**Comment by OrderedChaos-Dev** [comment]
Removed reference in beta4
