### ISSUE TITLE
[Crash][1.12.2-1.1.4] Ticking entity crashing server

### ISSUE THREAD

**Issue by Marlax0** [mc-jt9/ProjectVibrantJourneys#13]
Dedicated server crashes as soon as I join.

`java.lang.NoSuchMethodError: vibrantjourneys.entities.neutral.EntityGhost.getIsFading()Z`

Not happening in singleplayer.

Forge-14.23.4.2756

Crash log:
https://pastebin.com/28h9FHzV

Edit: Setting I:ghostSpawnWeight= to 0 works as a temporary workaround.

**Comment by mc-jt9** [comment]
Just took a look, the issue was due to some sloppy programming practices. Sorry, about that. I'm surprised it made it this far before it was found. I'll release v1.1.5 soon with a bunch of bugfixes.

**Comment by Marlax0** [comment]
It's no problem!
I love the concept of this mod and it would be a shame if someone passed it up because a few bugs never got reported.

**Comment by mc-jt9** [comment]
Fixed in v1.1.5
