### ISSUE TITLE
Server Crash - 1.16.5 - Fallen Log Generation

### ISSUE THREAD

**Issue by Darkfiend009** [mc-jt9/ProjectVibrantJourneys#132]
Minecraft: 1.16.5
P:VB: 3.0.0
Forge: 36.1.0

Looks like the server crash happened due to generating a fallen log.

https://pastebin.com/yUHC5DK5

**Comment by OrderedChaos-Dev** [comment]
I'm a little busy atm but I'll take a look asap

**Comment by OrderedChaos-Dev** [comment]
Should be fixed!
