### ISSUE TITLE
Website for 1.15+ has a bad security cert and is innaccessible on most browsers.

### ISSUE THREAD

**Issue by Ozzuneoj** [mc-jt9/ProjectVibrantJourneys#133]
As the title says, the website for 1.15+ linked on this page is blocked on most browsers because of an invalid security certification:
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/wiki

Since that seems to be the only place to find information about the current version of this mod, this is a pretty big problem. There is nothing on curseforge or anywhere else as far as I can tell... only downloads and change logs.

Please check this out. Thank you! :)

**Comment by OrderedChaos-Dev** [comment]
That's because I'm an idiot and put the wrong link. It's fixed now. There is a link on the CurseForge page at the top menu along with source/issues/etc

**Comment by Ozzuneoj** [comment]
I see, thank you for fixing it! :)
