### ISSUE TITLE
Compact,

### ISSUE THREAD

**Issue by pwigary** [mc-jt9/ProjectVibrantJourneys#134]
**Deleted Comment**

**Comment by pwigary** [comment]
Nvm, it's not simple. But making the things destroy randomly, when there is a not a "clear" weather, might be good compact for [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) and [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons). :)

**Comment by OrderedChaos-Dev** [comment]
I think having these things destroy dynamically, such as through weather events, might not be a good idea unless there was a way to regenerate the resources (e.g. chopping down a tree drops fallen leaves/twigs) which is something I've considered but not exactly getting into at the moment.
