### ISSUE TITLE
Bark mushroom infinite harvest

### ISSUE THREAD

**Issue by Krampus69** [mc-jt9/ProjectVibrantJourneys#137]
Hello,
First of all thank you for making the right-click harvest the objects instead of changing their skin. I have noticed that right clicking bark mushroom is giving you the item but it is not removing it from the tree. Which makes it infinite fuel right now.

Either way, thanks for this update. Me and my team were waiting for this :)

**Comment by OrderedChaos-Dev** [comment]
Uploading a fix to CurseForge now, thanks for letting me know!
