### ISSUE TITLE
Massive amount of log spam, potentially also related to datapack failing issues on game restart.

### ISSUE THREAD

**Issue by Darkmega18** [mc-jt9/ProjectVibrantJourneys#138]
G'day, I'm using:
**Vibrant Journeys: 3.0.3
Forge: 36.1.23
Minecraft: 1.16.5**

I have an issue where recently after I installed some mods I've been having a massive amount of console spam related to a nullpointer vibrant seems to be having against one of them that I installed. it's a custom modpack, but if you need me to I can send a copy of it you can load into multiMC or Curseforge to see what it contains.

I have reason to believe it started occurring after I installed "The Abyss: Chapter II" and it's Addon "The abyss the beginning". Could be not liking it's biome or dimension perhaps?

https://pastebin.com/Mm8eqibN

I also just tried to re-enter my world and I have a weird null that occurs related to biome generator which is potentially due to this collision breaking something. So I also put it in the log excerpt I sent. the world plays normally first, but the spam still occurs. But then on relog it was broken and gave me one of these:
https://cdn.discordapp.com/attachments/528429004630523904/846348466196054036/unknown.png

**Comment by Darkmega18** [comment]
ok, I have confirmed that the log spam occurs when abyss and journeys exist together. however my datapack failure to load doesn't seem to be the same issue, or atleast it didn't fix when I removed abyss.

**Comment by elias-knodel** [comment]
Can confirm. Our server gets spammed with over 15k NullPointer errors in the logs. Maybe a problem with the newest mod versions? 

Currently i am using:
**Vibrant Journeys**: 3.0.3
**Forge**: 36.1.18
**Minecraft**: 1.16.5
**The Abyss 2**: 1.9.7

**Comment by Darkmega18** [comment]
As a follow up, the mod "Blame" in singleplayer also has some read outs it sends to the logs related to Vibrant Journey's which support these things. it says something about the biome feature isn't registered.

one such read out.
https://pastebin.com/bSxPn9nC

**Comment by OrderedChaos-Dev** [comment]
@Darkmega18 The spamming shouldn't affect gameplay or be causing issues. The mod will test each biome's features to see if it can match with a tree feature so it can mark the biome to have fallen trees. When this fails, it'll skip the feature and go on to the next. It will do this testing and matching multiple times per biome when the game or world is loaded.
Also for line 252 in your log: (java.lang.NullPointerException: null
	at net.minecraft.world.biome.BiomeGenerationSettings.func_242492_a(BiomeGenerationSettings.java:86) ~[?:?])
This error was caused when trying to load a structure, which crashed your game.

@elias-knodel For the configured feature not being registered, I don't know why it's saying that because it is registered, along with the other features and I haven't actually seen that show up before.

**Comment by Darkmega18** [comment]
there isn't a crash though. I'm just showing you that there is a log spam which can be annoying to deal with when trying to watch for other issues. not all issues are crashes. (as numerous of issues I've had in a past few days have shown to be. :V)

It's also to ask how to fix it. cause generally log spam implies something is going wrong quite a lot.

**Comment by OrderedChaos-Dev** [comment]
Ah, I meant it's what is causing your world to not load. 
Sorry for the log spam, I didn't think it would scale that much. There will be an update out soon that will remove the log spamming.

**Comment by Darkmega18** [comment]
also is there anything to worry about or that you can do about what that blame mod's log is reporting about? the thing about "configuredfeature isn't registered" and it pointing to some of your fallen log features and such. you'd have to install it yourself with your mod and read the latest log to find out exactly which and how many other features there were having potential issues though.

**Comment by OrderedChaos-Dev** [comment]
I'll check it out, but there shouldn't be anything to worry about.
