### ISSUE TITLE
Issues with structure gel

### ISSUE THREAD

**Issue by Blacksky649** [mc-jt9/ProjectVibrantJourneys#139]
Seems to be an issue with projectvibrantjourneys-1.16.5-3.1.0BETA and structure gel. It was working fine prior to the current beta changes. Here is the log. Thanks for the hard work!

[crash-2021-05-25_07.33.57-fml.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6540127/crash-2021-05-25_07.33.57-fml.txt)

**Comment by OrderedChaos-Dev** [comment]
Does it load without vibrant journeys? I can't find anything in the log that shows a link between Structure Gel and PVJ, it just shows a crash from trying to register the rendering for the end portal block.

**Comment by Blacksky649** [comment]
Seems to work now, prob like you said something else acting up but structure gel came up in the error message after adding the beta version. Sorry for the worry >.<

**Comment by OrderedChaos-Dev** [comment]
No problem, glad it got sorted out!
