### ISSUE TITLE
[1.12.2-1.1.4] Some worldgen not working on dedicated servers

### ISSUE THREAD

**Issue by Marlax0** [mc-jt9/ProjectVibrantJourneys#14]
Multiplayer, flew around a fresh world for about 20 minutes and didn't see any of the new mod-added worldgen.
No rocks, twigs, leaf piles, etc. I did come across a prairie, so the biomes seem to be working.
Loaded the same seed into singleplayer and found the new stuff as soon as I spawned.
I'm not familiar enough with the mod yet to know what else might be missing.

Both server and client have B:modifyDungeons= set to false, in case that is related.

Edit: After generating 3 different worlds on my server without any new worldgen, I feel pretty confident saying this is a bug, and not just incredibly bad luck.

**Comment by mc-jt9** [comment]
Fixed in v1.1.5, sorry about that. I had world gen stuff running on client code instead of server code because I'm stupid haha
