### ISSUE TITLE
Crash by clicking on "create new world"

### ISSUE THREAD

**Issue by agentwolf88** [mc-jt9/ProjectVibrantJourneys#140]
[crash-2021-06-01_20.25.05-client.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6579816/crash-2021-06-01_20.25.05-client.txt)

**Comment by OrderedChaos-Dev** [comment]
Looks like something wrong with Dynamic Trees and this mod, but I don't know why it would do that. I'll take a look.

**Comment by OrderedChaos-Dev** [comment]
Fixed in new version, I think
