### ISSUE TITLE
Fireflies stay on the ground

### ISSUE THREAD

**Issue by Matthysse** [mc-jt9/ProjectVibrantJourneys#146]
Hello!
Maybe it's an already known issue, but the fireflies don't fly, and stay only on the ground. Could be a lot more immersive to have them flying around in groups, would be awesome!
Here is what happens in the current version:
![2021-07-03_13 25 56](https://user-images.githubusercontent.com/32510957/124352740-91420380-dc02-11eb-8729-06fcc511275a.png)

**Comment by OrderedChaos-Dev** [comment]
Do you have a mod list I can look at? From my experience this is probably an unintended interaction between AI/optimization mods.

**Comment by OrderedChaos-Dev** [comment]
This is a problem with AI optimization mods, nothing I can do about it
