### ISSUE TITLE
[Incompatibility] Project: Vibrant Journeys + Treasure2

### ISSUE THREAD

**Issue by Saintbrew** [mc-jt9/ProjectVibrantJourneys#147]
Hello, hope everything is okay, I have a problem and I don't know exatcly what is causing it, but everytime i use the two mods together it gives a error on startup of minecraft.

Crash log + Mod List : https://paste.dimdev.org/cuwarefufo.mccrash / mirror: https://paste.ee/p/FkQ1E

I have posted this same issue on the other mod github too.

**Comment by OrderedChaos-Dev** [comment]
You've reached past the limit of 4096 block ids, which any mod that adds blocks contributes to, so you'll need to remove some mods until you're below the limit.

**Comment by Saintbrew** [comment]
Thank you very much, i didn't know that, i i'll remove the issue from the other github

**Comment by Kasia1403** [comment]
@Saintbrew You must add JEID or NEID mod to Your modpack.
