### ISSUE TITLE
Game Crash Error 0 - Ticking Entity: Small Spider

### ISSUE THREAD

**Issue by Mewcenary** [mc-jt9/ProjectVibrantJourneys#148]
@OrderedChaos-Dev 
@JokerDima 

[crash-2021-07-03_07.17.42-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6767437/crash-2021-07-03_07.17.42-server.txt)
[crash-2021-07-05_21.41.34-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6767443/crash-2021-07-05_21.41.34-server.txt)

I've had to remove the mod to play.  Can't wait for a fix, I really like the mod! Besides the ticking issue, I also have the same issue with the fireflies staying on the ground as well.  Mod list is at the bottom.

-edit-
snipped crash report text

**Comment by OrderedChaos-Dev** [comment]
The first crash report is an incompatibility with Spiders 2.0. I'll see if I can fix it.
The second report is the Mahou Tsukai mod is trying to treat the small spiders from this mod as a player, which it obviously isn't so the game is crashing. I can't help with that and the mod isn't open sourced so I can't find the problem with it.
A temporary fix would be to disable the small spiders in the config to stop them from spawning.

I'm guessing the issue with fireflies is an AI optimization mod is messing with it. I noticed it too in my own personal modpack, but they fly around find in my dev environment. If you have any mods like that, see if you can blacklist the fireflies in their configs and maybe that will fix it.

**Comment by Mewcenary** [comment]
> The first crash report is an incompatibility with Spiders 2.0. I'll see if I can fix it.
> The second report is the Mahou Tsukai mod is trying to treat the small spiders from this mod as a player, which it obviously isn't so the game is crashing. I can't help with that and the mod isn't open sourced so I can't find the problem with it.
> A temporary fix would be to disable the small spiders in the config to stop them from spawning.
> 
> I'm guessing the issue with fireflies is an AI optimization mod is messing with it. I noticed it too in my own personal modpack, but they fly around find in my dev environment. If you have any mods like that, see if you can blacklist the fireflies in their configs and maybe that will fix it.

Okay, thank you very much! I'll try that.  I'll contact that mod creator next.

**Comment by stepsword** [comment]
Thanks for sending them my way! It's my fault for not doing a safer cast, though I hadn't expected random mobs to get and try to use my bow lol

Edit:
By the way, my flying entities also drifted towards the ground whenever performant was installed, about a year ago. Try removing that one and see if it works

**Comment by Mewcenary** [comment]
Any update on the fix?

**Comment by OrderedChaos-Dev** [comment]
I don't think there's anything on my end I can do to fix it. I'll keep this issue up in case I find anything, though

**Comment by OrderedChaos-Dev** [comment]
No updates on this issue for a while, so closing it.
Might re-write the small spiders completely to avoid these issues in the future
