### ISSUE TITLE
[1.16.5-3.2.0BETA] Broken configuredfeatures in ProjectVibrantJourneys is breaking Repurposed Structures and possibly other mods with configuredfeatures

### ISSUE THREAD

**Issue by TelepathicGrunt** [mc-jt9/ProjectVibrantJourneys#150]
Hello! I am the developer of Repurposed Structures and I got this bug report regarding the new beta of ProjectVibrantJourneys: https://github.com/TelepathicGrunt/RepurposedStructures/issues/118

I ran your mod with mine on as well as Blame. What Blame found was these three configuredfeatures were failed to be parsed:

projectvibrantjourneys:mega_redwood_tree
projectvibrantjourneys:redwood_tree
projectvibrantjourneys:redwood_forest_vegetation

Due to how Minecraft handles errors poorly, the error cascaded through the configuredfeature parsing and made the game refuse to parse my configuredfeatures, which in turn, broke my mod badly with many things no longer generating in my mod and in some cases, crashes.

The log with Blame, Repurposed Structures, and ProjectVibrantJourneys: https://paste.ee/p/BHoxa

Also, projectvibrantjourneys:fallen_tree_feature needs to be registered as well so registered configuredfeatures wont be silently removed from biomes (although this isn't the cause of my configuredfeatures not being parsed)

I hope this is enough info to help! Let me know if you get stuck and I'll try and assist

**Comment by OrderedChaos-Dev** [comment]
That's weird, I have the redwood features registered [here](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/1.16/src/main/java/projectvibrantjourneys/init/world/PVJConfiguredFeatures.java#L547) but I did forget to registered the fallen tree feature. I also can't find anything that would make the redwoods in particular fail to register, since all the other features are formatted the same way.

**Comment by TelepathicGrunt** [comment]
I think it's less of registration of the redwood tree but something about the redwood tree itself is unable to be parsed. I see that two of the trunk places have the exact same registration name so this may be causing the issue as one trunk placer will not be registered which would make the game choke upon trying to parse the tree with the unregistered trunk
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/84e1c0707c66232f86c9ca1c728b15dc24211136/src/main/java/projectvibrantjourneys/init/world/PVJBlockPlacers.java#L45-L46

try fixing that and see if the issue is resolve. You can give me a test jar and I can test if you prefer

**Comment by OrderedChaos-Dev** [comment]
Fixed it :D It wasn't the duplicate names, it was actually that I went over the allowed int range for tree trunk height:
`[net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Value 30 outside of range [0:24]; Value 40 outside of range [0:32]; Base value out of range: 25 [0-16]`

Going to upload the fix to CurseForge now.
