### ISSUE TITLE
Wrong loot table for frog

### ISSUE THREAD

**Issue by aburone** [mc-jt9/ProjectVibrantJourneys#153]
From debug.log
****************** Blame Report Loot Table 1.16.5-3.2.5-forge ******************

 Found a Loot Table path that does not exist:  projectvibrantjourneys:entities/frog
 The path represented by this Loot Table is:  data/projectvibrantjourneys/loot_tables/entities/frog.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location. (Although this could be intentional by mod author)
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by OrderedChaos-Dev** [comment]
Should be fixed in latest version
