### ISSUE TITLE
Missing loot table for flies and other wildlife

### ISSUE THREAD

**Issue by cheshyrp** [mc-jt9/ProjectVibrantJourneys#154]
Blame reports missing loot tables for flies, bats, frogs, slugs snails and other critters introduced by this mod.
Also for red sandstone rocks.

****************** Blame Report 1.16.5-3.2.3-forge ******************

 Found a Loot Table path that does not exist:  projectvibrantjourneys:entities/fly
 The path represented by this Loot Table is:  data/projectvibrantjourneys/loot_tables/entities/fly.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

 Found a Loot Table path that does not exist:  projectvibrantjourneys:entities/night_bat
 The path represented by this Loot Table is:  data/projectvibrantjourneys/loot_tables/entities/night_bat.json
 Loot Table method called at:  net.minecraft.entity.LivingEntity.func_213354_a
                               net.minecraft.entity.MobEntity.func_213354_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

 Found a Loot Table path that does not exist:  projectvibrantjourneys:blocks/red_sandstone_rocks
 The path represented by this Loot Table is:  data/projectvibrantjourneys/loot_tables/blocks/red_sandstone_rocks.json
 Loot Table method called at:  net.minecraft.block.AbstractBlock.func_220076_a
                               net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by OrderedChaos-Dev** [comment]
Should be fixed in the latest version
