### ISSUE TITLE
Configured feature not registered (fallen tree)

### ISSUE THREAD

**Issue by cheshyrp** [mc-jt9/ProjectVibrantJourneys#155]
Blame reports that at least one feature (fallen tree) was not registered, which can break worldgen for other mods.

****************** Blame Report 1.16.5-3.2.3-forge ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

```
 JSON info : {
  "config": {
    "feature": {
      "config": {
        "feature": {
          "config": {},
          "type": "projectvibrantjourneys:fallen_tree_feature"
        },
        "decorator": {
          "config": {},
          "type": "minecraft:top_solid_heightmap"
        }
      },
      "type": "minecraft:decorated"
    },
    "decorator": {
      "config": {
        "count": 0,
        "extra_chance": 0.05,
        "extra_count": 1
      },
      "type": "minecraft:count_extra"
    }
  },
  "type": "minecraft:decorated"
}
```

 Biome affected : [byg:enchanted_grove, environmental:marsh, minecraft:savanna_plateau, terraforged:shattered_savanna_scrub, byg:redwood_mountains, minecraft:savanna, byg:sierra_range,
                   byg:allium_fields, minecraft:desert_hills, byg:meadow, environmental:blossom_valleys, byg:grassland_plateau, byg:prairie_clearing, byg:wooded_meadow,
                   byg:wooded_red_rock_mountains, byg:flowering_meadow, byg:flowering_enchanted_grove, byg:red_desert, minecraft:sunflower_plains, atmospheric:rocky_dunes, byg:sierra_valley,
                   autumnity:pumpkin_fields, byg:grove, atmospheric:flourishing_dunes, minecraft:shattered_savanna_plateau, minecraft:desert, atmospheric:dunes_hills, atmospheric:dunes,
                   byg:mojave_desert, minecraft:shattered_savanna, byg:autumnal_valley, byg:amaranth_fields, minecraft:modified_wooded_badlands_plateau, byg:prairie, byg:baobab_savanna,
                   byg:lush_tundra, environmental:mushroom_marsh, byg:rose_fields, byg:lush_red_desert, minecraft:plains, byg:red_rock_mountains, atum:dead_oasis,
                   byg:wooded_grassland_plateau, atmospheric:rocky_dunes_hills, atmospheric:petrified_dunes, byg:orchard, minecraft:wooded_badlands_plateau, byg:flowering_grove, byg:shrublands]

**Comment by OrderedChaos-Dev** [comment]
This was fixed in the latest version
