### ISSUE TITLE
Aspen trees have oak branches

### ISSUE THREAD

**Issue by Matthysse** [mc-jt9/ProjectVibrantJourneys#157]
Hello!
I don't think if it's intended, but as the title says:
![2021-08-11_14 26 15](https://user-images.githubusercontent.com/32510957/129397851-f80f7ad0-9b3c-4f1a-b98b-8e5d2a4e98e6.png)

**Comment by OrderedChaos-Dev** [comment]
Oops, fixed this in today's update
