### ISSUE TITLE
Leaves Despawning

### ISSUE THREAD

**Issue by Tyrius1** [mc-jt9/ProjectVibrantJourneys#158]
At title says, the leaves on the trees are de-spawning. Not entirely sure if it's a mod conflict or what just yet but figured i'd report and as i find more info i'll report back here. I noticed it first when I tp'd to blossoming fields in creative.
Other modded trees don't appear to have the same issue.

projectvibrantjourneys-1.16.5-3.2.3
forge - 36.2.2
minecraft 1.16.5

**Comment by OrderedChaos-Dev** [comment]
This is because sometimes the leaves generate too far from a log so they start despawning. It won't cause any issues, you'll just have the outer leaves of some trees despawn. I'll need to reconfigure the leaves later

**Comment by starryfae** [comment]
There's a slight issue, hundreds and hundreds of saplings on the ground in newly generated chunks because of this. So /killitems is frequently used to reduce lag

**Comment by OrderedChaos-Dev** [comment]
I forgot that things like fast leaf decay exists

**Comment by OrderedChaos-Dev** [comment]
Uploading a fix to CurseForge. I reduced the radius of leaves on cherry blossom trees so there is a visual change but it should be fixed
