### ISSUE TITLE
[Mod Support] Diet

### ISSUE THREAD

**Issue by ghost** [mc-jt9/ProjectVibrantJourneys#159]
Any chance you could add support for [Diet](https://github.com/TheIllusiveC4/Diet/)?

**Comment by ghost** [comment]
You can close this. [TheIllusiveC4](https://github.com/TheIllusiveC4) added support for P:VJ in the latest version of Diet.

**Comment by OrderedChaos-Dev** [comment]
Ah, I had done it earlier but just forgot to upload the update. Good to know :P
