### ISSUE TITLE
Crimson Thicket not generating trees

### ISSUE THREAD

**Issue by BigBullmoose** [mc-jt9/ProjectVibrantJourneys#160]
Didn't have this issue until recently, one of the latest updates mustve caused it. Crimson Thickets just dont have any trees at all, just some grass and flower patches. Using a BOP worldtype but that wasn't an issue for me before.

![image](https://user-images.githubusercontent.com/65634364/130319273-bd3ba07b-0d66-4c86-ae8b-ec3ad5be4cce.png)

**Comment by BigBullmoose** [comment]
only thing ive done is disabled palm trees in the config, not sure if that might have bunked it up

**Comment by OrderedChaos-Dev** [comment]
Uploading a fix to CurseForge, thanks for letting me know!
