### ISSUE TITLE
Features generate despite being disabled

### ISSUE THREAD

**Issue by Matthysse** [mc-jt9/ProjectVibrantJourneys#162]
Hello!
As the title says, some features still generate despite being disabled in the config folder, here are the example for the beach grass and the palm trees:
![Capture d’écran 2021-09-08 110339](https://user-images.githubusercontent.com/32510957/132480365-a7c08f6e-b6d0-4ba7-ac19-5774f6c3de8e.png)
![Capture d’écran 2021-09-08 110406](https://user-images.githubusercontent.com/32510957/132480383-27c4a8e5-a73f-484f-a1e1-087c30f2cb94.png)
![2021-08-24_19 45 37](https://user-images.githubusercontent.com/32510957/132480412-503386ba-e702-46ce-b96c-0896da75a812.png)
![2021-09-08_10 55 48](https://user-images.githubusercontent.com/32510957/132480426-2ccbe43e-124a-4926-96e2-f7541e94f396.png)

**Comment by OrderedChaos-Dev** [comment]
This was actually intended since they are meant to be part of these biomes features, but I'll have them disabled based on the config as well.

**Comment by OrderedChaos-Dev** [comment]
Fixed
