### ISSUE TITLE
Missing Frog Texture

### ISSUE THREAD

**Issue by AetheriMC** [mc-jt9/ProjectVibrantJourneys#165]
It would seem that the frog is missing a texture.

![2021-10-02_09 31 45](https://user-images.githubusercontent.com/64112227/135727170-599d8df7-8a40-4b70-97bf-5541ee288269.png)

Project Vibrant Journeys v1.16.5-3.2.2

**Comment by OrderedChaos-Dev** [comment]
This was fixed in 3.2.3
