### ISSUE TITLE
Biomes still spawn

### ISSUE THREAD

**Issue by ORAMBOas** [mc-jt9/ProjectVibrantJourneys#167]
![image](https://user-images.githubusercontent.com/70290058/140652472-e9574c6b-f1fa-4dc0-a1f7-9412e9315593.png)
I have disabled biomes in config by they still spawning in the world

**Comment by ORAMBOas** [comment]
version of mod 
projectvibrantjourneys-1.16.5-3.2.10.jar

**Comment by OrderedChaos-Dev** [comment]
Hmm do you happen to have Terraforged?

**Comment by ORAMBOas** [comment]
Yes

**Comment by OrderedChaos-Dev** [comment]
This should help
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/163
