### ISSUE TITLE
Fallen Leaves are resistant to creeper explosions

### ISSUE THREAD

**Issue by ekiplier** [mc-jt9/ProjectVibrantJourneys#168]
What the title says. If a creeper explodes near or even on top of Fallen leaves, it leaves a hole on the ground with floating Fallen Leaves in the middle of it. It's not a big deal, it just feels kinda wrong as it doesn't make much sense that that block is more resistant to explosions than dirt. On the other hand, it's not resistant to TNT explosions

**Comment by OrderedChaos-Dev** [comment]
I'm unable to replicate this issue, at least in 1.16.5
