### ISSUE TITLE
PVJ stops generating after some x distance away from spawn. 1.12.2

### ISSUE THREAD

**Issue by ghost** [mc-jt9/ProjectVibrantJourneys#171]
Title. Not sure why, but PVJ always tends to generate perfectly around the spawn area, but stops when you start to travel outwards. Somewhere around 1,000 blocks maybe? I can't tell if there is a hard line. But if I use /tp to get some distance, it's obvious the generation comes to a complete halt for PVJ for some reason.

Console shows no errors in config or anything like that. It _works_, then suddenly stops working.

**Comment by OrderedChaos-Dev** [comment]
Can't replicate this, plus this report is pretty old since I didn't see it, so closing it.
