### ISSUE TITLE
Issues with world generation (1.18.1)

### ISSUE THREAD

**Issue by ghost** [mc-jt9/ProjectVibrantJourneys#172]
Rocks (also twigs and probably others too) that generate in snowy biomes replace snow but leave the grass block below as snowy.

(this is what a snowy grass block without snow on top looks like)
![kuva](https://user-images.githubusercontent.com/98822450/155306561-8f502562-fedc-432c-a4d1-8d40931de41e.png)
![kuva](https://user-images.githubusercontent.com/98822450/155307896-be6aff92-6b4e-49ff-b070-8ffce6b4eaef.png)

**Comment by ghost** [comment]
Found these also:
![kuva](https://user-images.githubusercontent.com/98822450/155310654-6c520aef-ea4b-4a08-a493-afc5e152a722.png)
![kuva](https://user-images.githubusercontent.com/98822450/155310772-eb9a25a6-96bc-4c75-99b7-3cb2605f5a89.png)

**Comment by ghost** [comment]
Seagrass and lily pads generating in frozen rivers. Caused by `enableExtraLilypads` and `enableExtraSeagrass`:
![kuva](https://user-images.githubusercontent.com/98822450/155313270-67887f11-8c59-4fb9-9e1a-52acf83b6efe.png)

**Comment by OrderedChaos-Dev** [comment]
I think I might've fixed these, or at least most of them I hope
