### ISSUE TITLE
[1.16.5, v3.2.11] Create Compat Issue

### ISSUE THREAD

**Issue by Elfinlocks** [mc-jt9/ProjectVibrantJourneys#173]
Hello! I believe some wood was missed in the Create compat integration. There doesn't seem to be Sawmill recipes for the following:

Cherry Blossom Log
Tamarack Log
Joshua Log

**Comment by OrderedChaos-Dev** [comment]
Moving the trees and stuff to a separate mod for later versions, so will keep track of that there
