### ISSUE TITLE
Compat with spiders 2.0

### ISSUE THREAD

**Issue by ekiplier** [mc-jt9/ProjectVibrantJourneys#175]
Idk how hard this would be to implement, but it would be really cool if the small mobs from pvj (like snails, slugs, and small spiders) had the same A.I. pattern from [Spiders 2.0.](https://www.curseforge.com/minecraft/mc-mods/spiders-2-0)

**Comment by OrderedChaos-Dev** [comment]
It's probably not gonna happen, I'm focusing on other things at the moment and those small mobs haven't been implemented in later versions yet
