### ISSUE TITLE
1.18.2 Ground Clutter Placement

### ISSUE THREAD

**Issue by Tyrius1** [mc-jt9/ProjectVibrantJourneys#178]
![2022-05-29_16 03 36](https://user-images.githubusercontent.com/29525146/170889385-8a3e8e2a-2dbc-4004-bf03-fbb10da5fd67.png)

Ground clutter placement could use some improvement. 😛 So far this has been the only issue i've noticed in the port.
Perhaps a tag in data to specify what blocks each of piece ground clutter can not be placed on?

**Comment by OrderedChaos-Dev** [comment]
Ah, yes it could use some work, I'll probably mess around with some tags to see what works best

**Comment by OrderedChaos-Dev** [comment]
2 years later I finally added a block tag for this
