### ISSUE TITLE
[1.18.2 suggestion] Add your biomes to biome tags for best compat

### ISSUE THREAD

**Issue by TelepathicGrunt** [mc-jt9/ProjectVibrantJourneys#179]
Hello, I am the dev for Repurposed Structures. I had noticed an issue with a few biome mods in 1.18.2 that my mod's structures and datapack structures are not spawning in the modded biomes.

In 1.18.2, Mojang allowed any worldgen registry to have tags. Including biomes. They then improved the json system for creating worldgen structures which now uses biome tags for what biomes to spawn in. As a result, biome mods not using these tags will not spawn modded or json structures that uses biome tags.

I have more info here along with resources on what biome tags are available to use and add to.
https://gist.github.com/TelepathicGrunt/b768ce904baa4598b21c3ca42f137f23

Just ask me if you get stuck or need help. The biome tags would go under /data//worldgen/biome/ folder

**Comment by OrderedChaos-Dev** [comment]
Hey, I did not know this, thanks for letting me know! 
Love your mods, btw!
