### ISSUE TITLE
[Feature Request] Right-click on ground cover does not change it in Survival mode

### ISSUE THREAD

**Issue by Ariannae** [mc-jt9/ProjectVibrantJourneys#18]
As title indicates, I'd like to suggest that right-clicking on ground cover objects while in Survival mode does not change them to a different variant. I believe that it's strange to be able to right-click on a bone (or rock, etc) in Survival and have it change.

**Comment by mc-jt9** [comment]
I'm trying to figure out the best way to handle how groundcover drops and which models can be used. Maybe might just make it so that it places a random model that cannot be changed.

**Comment by mc-jt9** [comment]
I was thinking of exactly that. I can also make it so that the player can change the model when in creative mode.

**Comment by mc-jt9** [comment]
Implemented in v1.3.0!
