### ISSUE TITLE
trying to strip (already) stripped logs from the mod crashes the game (1.18.2)

### ISSUE THREAD

**Issue by ghost** [mc-jt9/ProjectVibrantJourneys#181]
To reproduce: with an axe, right click a log from the mod:
- first time strips the log
- second time crashes the game

(tried it on baobab and maple)

[crash-2022-06-12_18.44.59-client.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/8886293/crash-2022-06-12_18.44.59-client.txt)

**Comment by Answordy** [comment]
Same here

**Comment by OrderedChaos-Dev** [comment]
Fixed in alpha 7 build, sorry for the long wait
