### ISSUE TITLE
WTHIT Lang Compatibility

### ISSUE THREAD

**Issue by firemaster1294** [mc-jt9/ProjectVibrantJourneys#183]
Hi! I’ve found an issue when using this mod with WTHIT (a successor to WAILA/HWYLA), as items will show up as block.projectvibrantjourneys.<name> when viewed in my crosshairs. JEI is working fine, but it seems that WTHIT isn’t pulling lang file properly. This is the only mod I’ve noticed this problem with. Any chance of getting a patch for this?

**Comment by OrderedChaos-Dev** [comment]
Fixed
