### ISSUE TITLE
[1.18.2] Crash client after used bone meal

### ISSUE THREAD

**Issue by DanteTooMayCry** [mc-jt9/ProjectVibrantJourneys#184]
Project Vibrant + Terrablender

Crash on every use bonemeal when also moded by: Enderchests and shetipiancore (both latest). No other mods, but datapacks: Terralith_v2.2.1 and Towers_Of_The_Wild_Reworked_v3.0.0_Waystones

Server not crashed. Only client (all mods are also on server).

Ver 1.18.2, Forge 40.1.48

https://www.curseforge.com/minecraft/mc-mods/enderchests    v1.18-1.9.5
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore   v1.18-3.10.10

**Comment by Edel-Lilies** [comment]
same but forge 40.1.57

**Comment by OrderedChaos-Dev** [comment]
I think I've fixed this, uploaded the fix
