### ISSUE TITLE
Farmer Villager ticking

### ISSUE THREAD

**Issue by Kangy1103** [mc-jt9/ProjectVibrantJourneys#185]
Hi,

My server crash reports point to PVJ causing a Farmer villager ticking when applying bonemeal.

Here's the crash report:
[crash-2022-07-17_01.43.59-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/9127257/crash-2022-07-17_01.43.59-server.txt)

**Comment by OrderedChaos-Dev** [comment]
I think I've fixed this, uploaded the fix
