### ISSUE TITLE
Feature Order Cycle

### ISSUE THREAD

**Issue by bageldotjpg** [mc-jt9/ProjectVibrantJourneys#186]
Here in [PVJWorldGenEvents.java](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/82021535658112d26eeab39d47fe38bf5ac428b5/src/main/java/com/projectvibrantjourneys/event/PVJWorldGenEvents.java#L85) you add Vanilla placed features to vanilla and other modded biomes. This can cause a feature order cycle error when playing with mods that add other biomes.
![image](https://user-images.githubusercontent.com/55970498/187459586-a71e04f0-8a2d-4628-928c-e66dbeccd078.png)
A fix for this that *should* prevent the crashing alongside other mods would be to duplicate those placed features but register them as your own in [PVJPlacements.java](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/82021535658112d26eeab39d47fe38bf5ac428b5/src/main/java/com/projectvibrantjourneys/core/registry/features/PVJPlacements.java). 

This should prevent this crash from happening alongside mods with biomes.
`java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:river]=net.minecraft.world.level.biome.Biome@5b2258ac`

**Comment by OrderedChaos-Dev** [comment]
Thanks for letting me know, should have a fix out soon.
