### ISSUE TITLE
The One Probe - Natural Cobweb (name)

### ISSUE THREAD

**Issue by AK-Chester** [mc-jt9/ProjectVibrantJourneys#187]
![pvj-cobweb](https://user-images.githubusercontent.com/112804655/188308695-b8a87b9d-aac7-4c8e-aee4-7944c99e2da0.jpg)

Probably related to [this](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/183) issue (?) ... bones, stones and twigs seem to be okay, though.

**Comment by OrderedChaos-Dev** [comment]
Fixed

**Comment by AK-Chester** [comment]
Thank you!
