### ISSUE TITLE
[1.18.2-4.1.1] Missing spawn in TerraForged or Terralith biomes

### ISSUE THREAD

**Issue by DRACTION** [mc-jt9/ProjectVibrantJourneys#188]
Hi, missing spawn for all in check
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/0f4bf962715378eaa17292ce3342a93b9f9ed8e3/src/main/java/com/projectvibrantjourneys/event/PVJWorldGenEvents.java#L62

Easy to reproduce (just install one of this mods and find their biomes).
And I see that you have disabled the biome tag check in 
```java	@SafeVarargs
	private boolean hasAnyTag(Optional<Holder<Biome>> biome, TagKey<Biome>... tags) {
//		for(TagKey<Biome> tag : tags) {
//			return biome.is(tag);
//		}
		return false;
	}
```
I see that `Optional<Holder<Biome>> biome` is sometimes empty...

I'm not a Java developer, but I believe you can handle it)))

**Comment by OrderedChaos-Dev** [comment]
I'm not really sure what this is asking for?
Edit: nevermind, I'll check it out
BTW tags are not available during the biome loading event which is the reason for disabling it
