### ISSUE TITLE
Biomes spawn even if their weights and/or toggle is off.

### ISSUE THREAD

**Issue by MagmaSlime123** [mc-jt9/ProjectVibrantJourneys#190]
Title.

Tested with/without other mods, same issue.

MC 1.16.5, Forge 36.2.39, and PVJ 3.2.11.

**Comment by MagmaSlime123** [comment]
Closing without responding isn't helpful.

**Comment by OrderedChaos-Dev** [comment]
The reported issue is from 2 years ago, on a version I don't develop on anymore.

**Comment by MagmaSlime123** [comment]
Because that was the only version you had at the time.

**Comment by OrderedChaos-Dev** [comment]
Sure, 2 years ago. But in the most recent version that is actively in development, this issue doesn't exist.

**Comment by MagmaSlime123** [comment]
I know we're busy sometimes, but I mean, 2 years is a long time for a response.

**Comment by OrderedChaos-Dev** [comment]
I'm not obligated to respond to anyone and no one is entitled to a response. This isn't a job, it's a hobby. I do this for free, and I don't even play the game anymore. If I want to take a break for a year or two, or quit modding indefinitely, I'm allowed to.
