### ISSUE TITLE
Essentials compatability

### ISSUE THREAD

**Issue by AdamNisbett** [mc-jt9/ProjectVibrantJourneys#194]
I love all the small birds this mod adds like the Little Grebe and Blue Jays.  One of the tools that the Essentials mod adds is a cage that allows you to capture/transport/release small mobs like chickens, rabbits, etc.  When attempting to use on a bird mob from this mod though it says it can only transport small mobs, so apparently whatever it's checking to determine classification isn't registering your birds as small mobs.  It would be nice if they could be classified in that way so that the Essentials mod's cage would work on them.

**Comment by OrderedChaos-Dev** [comment]
1.5 years late but this is the wrong mod lol
