### ISSUE TITLE
current translation of fashion into Russian language (ru_ru.json)

### ISSUE THREAD

**Issue by AltezaR** [mc-jt9/ProjectVibrantJourneys#198]
{
	"itemGroup.projectvibrantjourneys": "Project: Vibrant Journeys",
	
	"item.projectvibrantjourneys.twigs": "Ветки",
	"item.projectvibrantjourneys.fallen_leaves": "Опавшие листья",
	"item.projectvibrantjourneys.dead_fallen_leaves": "Мертвые опавшие листья",
	"item.projectvibrantjourneys.rocks": "Камни",
	"item.projectvibrantjourneys.mossy_rocks": "Замшелые камни",
	"item.projectvibrantjourneys.sandstone_rocks": "Песчаные камни",
	"item.projectvibrantjourneys.red_sandstone_rocks": "Красные песчаные камни",
	"item.projectvibrantjourneys.ice_chunks": "Куски льда",
	"item.projectvibrantjourneys.bones": "Кости",
	"item.projectvibrantjourneys.charred_bones": "Обугленные кости",
	"item.projectvibrantjourneys.pinecones": "Сосновые шишки",
	"item.projectvibrantjourneys.seashells": "Ракушки",
	
	"item.projectvibrantjourneys.sea_oats": "Морской овес",
	"item.projectvibrantjourneys.cattail": "Рогоз",
	"item.projectvibrantjourneys.bark_mushroom": "Гриб на коре",
	"item.projectvibrantjourneys.orange_bark_mushroom": "Оранжевый гриб на коре",
	"item.projectvibrantjourneys.light_brown_bark_mushroom": "Светлый гриб на коре",
	"item.projectvibrantjourneys.glowing_blue_fungus": "Светящийся синий гриб",
	"item.projectvibrantjourneys.glowcap": "Светошляпка",
	"item.projectvibrantjourneys.crimson_nettle": "Багровая крапива",
	"item.projectvibrantjourneys.warped_nettle": "Искаженная крапива",
	"item.projectvibrantjourneys.cindercane": "Пепельный тростник",
	"item.projectvibrantjourneys.short_grass": "Короткая трава",
	"item.projectvibrantjourneys.beach_grass": "Пляжная трава",
	"item.projectvibrantjourneys.small_cactus": "Маленький кактус",
	"item.projectvibrantjourneys.prickly_bush": "Колючий куст",
	"item.projectvibrantjourneys.reeds": "Камыш",
	"item.projectvibrantjourneys.icicle": "Сосулька",
	
	"item.projectvibrantjourneys.oak_hollow_log": "Дубовое полое бревно",
	"item.projectvibrantjourneys.birch_hollow_log": "Березовое полое бревно",
	"item.projectvibrantjourneys.spruce_hollow_log": "Еловое полое бревно",
	"item.projectvibrantjourneys.jungle_hollow_log": "Полое бревно тропического дерева",
	"item.projectvibrantjourneys.acacia_hollow_log": "Акациевое полое бревно",
	"item.projectvibrantjourneys.dark_oak_hollow_log": "Полое бревно тёмного дуба",

	"item.projectvibrantjourneys.potted_small_cactus": "Маленький кактус в горшке",
	"item.projectvibrantjourneys.potted_cindercane": "Пепельный тростник в горшке",
	"item.projectvibrantjourneys.potted_warped_nettle": "Искаженная крапива в горшке",
	"item.projectvibrantjourneys.potted_crimson_nettle": "Багровая крапива в горшке",
	"item.projectvibrantjourneys.potted_glowcap": "Светошляпка в горшке",
	"item.projectvibrantjourneys.potted_prickly_bush": "Колючий куст в горшке",
	
	"block.projectvibrantjourneys.twigs": "Ветки",
	"block.projectvibrantjourneys.fallen_leaves": "Опавшие листья",
	"block.projectvibrantjourneys.dead_fallen_leaves": "Мертвые опавшие листья",
	"block.projectvibrantjourneys.rocks": "Камни",
	"block.projectvibrantjourneys.mossy_rocks": "Замшелые камни",
	"block.projectvibrantjourneys.sandstone_rocks": "Песчаные камни",
	"block.projectvibrantjourneys.red_sandstone_rocks": "Красные песчаные камни",
	"block.projectvibrantjourneys.ice_chunks": "Куски льда",
	"block.projectvibrantjourneys.bones": "Кости",
	"block.projectvibrantjourneys.charred_bones": "Обугленные кости",
	"block.projectvibrantjourneys.pinecones": "Сосновые шишки",
	"block.projectvibrantjourneys.seashells": "Ракушки",
	
	"block.projectvibrantjourneys.natural_cobweb": "Паутина",
	"block.projectvibrantjourneys.sea_oats": "Морской овес",
	"block.projectvibrantjourneys.cattail": "Рогоз",
	"block.projectvibrantjourneys.bark_mushroom": "Гриб на коре",
	"block.projectvibrantjourneys.orange_bark_mushroom": "Оранжевый гриб на коре",
	"block.projectvibrantjourneys.light_brown_bark_mushroom": "Светлый гриб на коре",
	"block.projectvibrantjourneys.glowing_blue_fungus": "Светящийся синий гриб",
	"block.projectvibrantjourneys.glowcap": "Светошляпка",
	"block.projectvibrantjourneys.crimson_nettle": "Багровая крапива",
	"block.projectvibrantjourneys.warped_nettle": "Искаженная крапива",
	"block.projectvibrantjourneys.cindercane": "Пепельный тростник",
	"block.projectvibrantjourneys.short_grass": "Короткая трава",
	"block.projectvibrantjourneys.beach_grass": "Пляжная трава",
	"block.projectvibrantjourneys.small_cactus": "Маленький кактус",
	"block.projectvibrantjourneys.prickly_bush": "Колючий куст",
	"block.projectvibrantjourneys.reeds": "Камыш",
	"block.projectvibrantjourneys.icicle": "Сосулька",
	
	"block.projectvibrantjourneys.oak_hollow_log": "Дубовое полое бревно",
	"block.projectvibrantjourneys.birch_hollow_log": "Березовое полое бревно",
	"block.projectvibrantjourneys.spruce_hollow_log": "Еловое полое бревно",
	"block.projectvibrantjourneys.jungle_hollow_log": "Полое бревно тропического дерева",
	"block.projectvibrantjourneys.acacia_hollow_log": "Акациевое полое бревно",
	"block.projectvibrantjourneys.dark_oak_hollow_log": "Полое бревно тёмного дуба",

	"block.projectvibrantjourneys.potted_small_cactus": "Маленький кактус в горшке",
	"block.projectvibrantjourneys.potted_cindercane": "Пепельный тростник в горшке",
	"block.projectvibrantjourneys.potted_warped_nettle": "Искаженная крапива в горшке",
	"block.projectvibrantjourneys.potted_crimson_nettle": "Багровая крапива в горшке",
	"block.projectvibrantjourneys.potted_glowcap": "Светошляпка в горшке",
	"block.projectvibrantjourneys.potted_prickly_bush": "Колючий куст в горшке"
	
}

**Comment by OrderedChaos-Dev** [comment]
Kind of a year late but this should be a PR
