### ISSUE TITLE
Compatibility with everycompat mod.

### ISSUE THREAD

**Issue by KostromDan** [mc-jt9/ProjectVibrantJourneys#201]
This mod adds variants of hollow log for all bop/byg biomes and it would be nice to implement compatibility.
![image](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/90044015/4cd4f68b-8397-4560-96d1-5b1a9c035b63)

**Comment by OrderedChaos-Dev** [comment]
Didn't get around to this because of time but it's in the backlog. #211
