### ISSUE TITLE
Dimension blacklist in 1.12.2 PVJ v1.6.4 doesn't work

### ISSUE THREAD

**Issue by XvaleX10** [mc-jt9/ProjectVibrantJourneys#202]
If i put prehistoric nature mod ids in the dimension blacklist the pvj generation is blocked in the overworld
This is what I wrote in the blacklist:-79,-82,-86,-81,-85,-89,-87,-88,-83,-90,-78,-80,-84
Id separated by commas and no spaces as it says in the config file.
Log file
[latest.log](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/11926080/latest.log)

**Comment by SiverDX** [comment]
Don't think this will be fixed
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/124

**Comment by XvaleX10** [comment]
> Don't think this will be fixed #124

Unfortunately, I tried anyway
