### ISSUE TITLE
Feature Request: Config Option For Replaceable Blocks

### ISSUE THREAD

**Issue by Br00t4L17y** [mc-jt9/ProjectVibrantJourneys#206]
**The Problem:**
Items that generate on the ground (rocks, bones, twigs, moss etc) are physical blocks and require interaction to remove. When terraforming, this becomes very inconvenient to stop and manually remove the objects before placing dirt or other blocks.

**The Request:**
Add an option to the config to enable "replaceable blocks", that would make each of those blocks replaceable by putting a block into their space, much like vanilla grass and tall grass works.

**Comment by zen-crab** [comment]
This has gotten me killed on more than one occasion.

**Comment by OrderedChaos-Dev** [comment]
I'm assuming this is for 1.20? Just tested an option where this behavior is enabled by default, will upload it tonight

@Br00t4L17y apologies I did see this earlier but forgot. I also can't do anything about the moss since that's a vanilla block

**Comment by OrderedChaos-Dev** [comment]
Just uploaded for 1.20 and 1.21
