### ISSUE TITLE
Request: Configure ground drops per biome.

### ISSUE THREAD

**Issue by Skelex6464** [mc-jt9/ProjectVibrantJourneys#207]
Big fan of this mod, been using it for years.

I'm currently using it with Terralith, and in some biomes like Ancient Sands there are twigs and leaf piles everywhere despite this being a biome with no trees. Is there any way that this could be disabled per biome, or per biome tag? I am running this on 1.19.2 by the way.

Thank you.

**Comment by OrderedChaos-Dev** [comment]
You might be able to do this with a datapack, which is essentially how this mod knows where to generate what (see [example](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/1.19/src/generated/resources/data/projectvibrantjourneys/forge/biome_modifier/rocks.json)). You can see it generates in all overworld biomes except mushroom islands and icy biomes

**Comment by zen-crab** [comment]
> You might be able to do this with a datapack, which is essentially how this mod knows where to generate what (see [example](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/1.19/src/generated/resources/data/projectvibrantjourneys/forge/biome_modifier/rocks.json)). You can see it generates in all overworld biomes except mushroom islands and icy biomes

Would a datapack be able to prevent the mod from modifying the insides of structures?
