### ISSUE TITLE
Textures do not load properly with heavy modpacks (1.20.1)

### ISSUE THREAD

**Issue by snlumi** [mc-jt9/ProjectVibrantJourneys#208]
I really like this mode. Because it is a very good mod that enhances the experience without interfering with the gameplay.
However, adding this mod to some modpacks does not seem to load the textures properly. 
I have no way of finding out if this is a problem with the mod or the texture pack.
But one thing is certain: there are times when it loads properly and times when it doesn't.

How does this problem occur
1. I was playing on btm4 modpack. (With this mode added)
2. Once it's finished loading, it randomly appears as an error block in-game
It runs normally and the game is playable.
![2024-05-24_21 59 03](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/152872383/46b8a5de-b184-43b0-8171-14e5dbd0ec61)

**Comment by OrderedChaos-Dev** [comment]
Seems to be an issue with the modpack? Something is probably interfering with block rendering. I can't really help with that unfortunately.
