### ISSUE TITLE
Feature Request: Provide weights to control the generation of items

### ISSUE THREAD

**Issue by wumengzhixing** [mc-jt9/ProjectVibrantJourneys#209]
The number of items generated is too much, hopefully a weight can be given to control the amount of generation
![2024-06-18_18 49 26](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/88496786/57a66538-ffa6-48c7-a1d9-95271194ee2a)

**Comment by OrderedChaos-Dev** [comment]
I'll be adding more config options for 1.21 for more control

**Comment by wumengzhixing** [comment]
> I'll be adding more config options for 1.21 for more control

Hopefully 1.20.1 will sync this update

**Comment by OrderedChaos-Dev** [comment]
I don't do backports because of time. For the more barren biomes like the one in your screenshot (terralith I assume?), you can use a datapack to disable generation in those biomes

**Comment by wumengzhixing** [comment]
> I don't do backports because of time. For the more barren biomes like the one in your screenshot (terralith I assume?), you can use a datapack to disable generation in those biomes

Well, this is very bad news ......

**Comment by OrderedChaos-Dev** [comment]
Closing since this is in 1.21
