### ISSUE TITLE
1.3.1 world generation crash

### ISSUE THREAD

**Issue by Ariannae** [mc-jt9/ProjectVibrantJourneys#21]
Looks like I'm getting the following crash on world generation:

https://pastebin.com/MZwiZdq1

Pretty heavily modded setup, so it could potentially be an incompatibility.

**Comment by DonkeysWTF** [comment]
Yeah I am getting the same crash.

**Comment by mc-jt9** [comment]
I fixed the same crash in another spot, but I missed it somewhere else. I'm fixing it right now.

**Comment by mc-jt9** [comment]
Fixed in 1.3.2...hopefully. It shouldn't be in any other places.

**Comment by Ariannae** [comment]
Yup, 1.3.2 looks like it fixed the problem for me. No crashes and some fantastic new features. Keep up the good work. I'm really, really enjoying the additions from this, especially when coupled with [Dynamic Surroundings.](https://minecraft.curseforge.com/projects/dynamic-surroundings) It's like a brand new game.
