### ISSUE TITLE
New 1.21 version of neoforge didn't work with the current versions of the mods 

### ISSUE THREAD

**Issue by modpacka2** [mc-jt9/ProjectVibrantJourneys#210]
I need project : vibrant journeys for my modpack, but the version for the new 1.21 neoforge didn't work with the latest beta (I need the current neoforge version for kubeJS). I hope you can release a new patch for this soon. (I don't want to stress you, I just want to make sure you know that the current version have this issue).

![image](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/assets/75133238/06cdc37a-2160-4d27-940d-922c9ba52c3c)

I don't know the mod and what do you want but this is what to update :
https://github.com/neoforged/NeoForge/pull/971

**Comment by OrderedChaos-Dev** [comment]
Hi, I'm travelling right now but I'll fix this when I'm able to

**Comment by Gbergz** [comment]
Came to report the same thing, glad it is already. 👍

**Comment by OrderedChaos-Dev** [comment]
Just submitted an update to CurseForge, should be fixed now
