### ISSUE TITLE
Trees gone?

### ISSUE THREAD

**Issue by Velistraee** [mc-jt9/ProjectVibrantJourneys#214]
I dont know if it is just me or if the sakura trees just vanished from the game. Where are they? They are not in game and i have not been able to find them except in older versions of PVJ. There is no mention in the changelogs ive seen, that have a statement of removing the sakura trees. 
Where are they? Im mainly asking because atleast in my opinion, the 2 trees are far better than Minecraft's official ones and me and my buds are looking around for Project Vibrant Journey's Sakura trees and had to go into creative to notice they just were gone. Also i could find no thread talking about this in the bug reports.
Current version; 1.19.2, PVJ 5.1.2
Last used Version with Sakura trees in them; 1.16.5, PVJ 3.2.11

Edit; As i am writting this, i have also noticed that actually none of the trees are here. Fir, pine, willow, etc. they are not on a newer version either.

**Comment by OrderedChaos-Dev** [comment]
I separated all the trees/biomes to another mod: https://legacy.curseforge.com/minecraft/mc-mods/pioneer

**Comment by Velistraee** [comment]
Thank you so much!

**Comment by Velistraee** [comment]
Did the sakura trees get removed, btw? I still cannot find them.
