### ISSUE TITLE
stop decorations from spawning on top of bedrock layer, nether

### ISSUE THREAD

**Issue by VaporeonScripts** [mc-jt9/ProjectVibrantJourneys#216]
![image](https://github.com/user-attachments/assets/cd59cab9-63f6-469b-88e2-2051dcadf952)

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .84

**Comment by OrderedChaos-Dev** [comment]
Hi, I'm travelling right now but will get to this next week

**Comment by OrderedChaos-Dev** [comment]
Just uploaded an update for this on curseforge
