### ISSUE TITLE
Small animal spawn rate is absolutely insane

### ISSUE THREAD

**Issue by Sunconure11** [mc-jt9/ProjectVibrantJourneys#23]
![screenshot 2018-09-16 08 22 13](https://user-images.githubusercontent.com/5614902/45596425-ce717400-b989-11e8-9de5-3b8fe021ab4b.png)

**Comment by mc-jt9** [comment]
Well that is super weird. I think the tall grass masked most of them during testing. A permanent fix for this is to just lower the spawn weights in the config until I get a more permanent fix out.

**Comment by crazyirishwrencher** [comment]
I noticed that even when set to 0, they still spawn.

**Comment by mc-jt9** [comment]
Lowered spawn rate in 1.4.0, reset your config.

**Comment by crazyirishwrencher** [comment]
![2018-11-23_13 35 34](https://user-images.githubusercontent.com/34118405/48957120-c5ba9280-ef24-11e8-81b2-cbd27cfd62bd.png)
This is in 1.4.0. Generated a Flat World to do some experimenting. Doesn't seem to generate these quantities in a regular world.
