### ISSUE TITLE
Shelf fungus spawning does not appear to be disableable

### ISSUE THREAD

**Issue by xkforce** [mc-jt9/ProjectVibrantJourneys#29]
**Describe the bug**
Setting bracketFungusDensity=0 does not disable the generation of shelf fungus on fallen tree logs as expected.

**Comment by mc-jt9** [comment]
Oops, sorry. I'll add a fix in the next update.

**Comment by xkforce** [comment]
Thank you.

**Comment by mc-jt9** [comment]
Fixed in 1.4.0
