### ISSUE TITLE
[Crash][1.12.2-1.0.1] Game crashes if a spawn is set to 0

### ISSUE THREAD

**Issue by Mike-U5** [mc-jt9/ProjectVibrantJourneys#3]
**Describe the bug**
Setting a mob spawn to 0 in the config causes an infinite tick loop.
No other mods are used.

**Crash Logs**
> java.lang.IllegalArgumentException
> 	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
> 	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
> 	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:266)
> 	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
> 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
> 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
> 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by mc-jt9** [comment]
Fixed in v1.1.0
