### ISSUE TITLE
Mod Interaction: Flies trigger footstep noises in Dynamic Surroundings.

### ISSUE THREAD

**Issue by crazyirishwrencher** [mc-jt9/ProjectVibrantJourneys#30]
**Describe the bug**
With both PVJ & Dynamic Surroundings installed, Flies trigger footstep noises whenever they come close enough to a surface.

**Comment by crazyirishwrencher** [comment]
Unrelated, but flies also constantly get stuck in corners and die.

**Comment by mc-jt9** [comment]
I'll look into it. The fly dying in a corner thing is weird but I'm sure flies do stupid things like that in real life too.

**Comment by crazyirishwrencher** [comment]
The only reason I mention it is its loud. With a lot of flies about its like I'm hangin on the porch near one of those electric mosquito traps during peak season :)

**Comment by mc-jt9** [comment]
I'll make the death sound effect silent, haha

**Comment by mc-jt9** [comment]
Fixed in 1.4.0
