### ISSUE TITLE
Small Spiders consume wheat

### ISSUE THREAD

**Issue by crazyirishwrencher** [mc-jt9/ProjectVibrantJourneys#31]
**Describe the bug**
Small Spiders consume wheat. My cows weren't breeding nearly as quickly as normal. I use a Farming for Blockheads Feeding Trough for a nice semi-auto but still rustic cow farm. Spent a little time trying to figure out why and noticed some tiny spiders with heart particles. The Feeding Trough emits particles when an Item is consumed as well. The spiders will also eat from player hands. Humorous, but probably unintended.

![2018-10-01_17 45 37](https://user-images.githubusercontent.com/34118405/46317710-e52ae400-c5a1-11e8-9015-499ca3a187bc.png)

**Comment by mc-jt9** [comment]
That's...interesting. I'll fix it in the next update.
Beautiful world, by the way! It's the style of building I enjoy the most.

**Comment by mc-jt9** [comment]
Fixed in 1.4.0
