### ISSUE TITLE
PVJ Door crash/disconnect when updating map

### ISSUE THREAD

**Issue by phyne** [mc-jt9/ProjectVibrantJourneys#32]
I tried to update a map in-game after placing down PVJ doors in the area. My client was disconnected and am unable to reconnect due to my player holding the map. I can workaround the issue myself, but the log clearly indicated the disconnect because PVJ doors don't have a map color.

Server log of the disconnection: https://pastebin.com/kfmbxBuc

**Comment by mc-jt9** [comment]
Sorry about that, I'll fix it in the next update

**Comment by phyne** [comment]
Awesome! Thanks for the great mod.

**Comment by mc-jt9** [comment]
Fixed in 1.4.0
