### ISSUE TITLE
Incompat with BWM (every mod who depends on PVJ)

### ISSUE THREAD

**Issue by Rikshy** [mc-jt9/ProjectVibrantJourneys#33]
**Describe the bug**
https://github.com/mc-jt9/ProjectVibrantJourneys/blob/41233de4706a4a45f29ba9c5867655d8c7d1125b/src/main/java/vibrantjourneys/ProjectVibrantJourneys.java#L31

**Crash Logs**
https://hastebin.com/efinasukit.apache

BetterWIthMods latest updates contains a dependancy on PVJ. Do you really need to load after ALL mods?

**Comment by mc-jt9** [comment]
Hmm yeah I think I left that in to test something and I forgot to change it, sorry.

**Comment by primetoxinz** [comment]
Should be fixed then, can close this

**Comment by mc-jt9** [comment]
Alright fixed in v1.4.0, should only load after BoP and Traverse now.
