### ISSUE TITLE
Suggestion: Setting for global groundcover density

### ISSUE THREAD

**Issue by nickjackson-ff** [mc-jt9/ProjectVibrantJourneys#38]
Issue:
I want to reduce the overall presence of groundcover in the world, but adjusting the individual density settings for each variant of groundcover is a bit of a pain (there are a lot of variants, especially with BoP).

Suggestion:
A global setting for the density of all groundcover (or every variant of each groundcover type) would make this task easy to accomplish. It could work as a multiplier [0.0-1.0] for "normal" density.

**Comment by mc-jt9** [comment]
Ah yeah sounds great. Sorry for the late reply, I saw this when it was posted but forgot about it. Yeah, updates are coming slow because I'm busy with other things.

**Comment by mc-jt9** [comment]
This mod isn't dead! Just taking a break. Global density for nearly everything added in v1.5.0!
