### ISSUE TITLE
Mod stone (and most other blocks) break far too easily...

### ISSUE THREAD

**Issue by ate0ate** [mc-jt9/ProjectVibrantJourneys#39]
I apologize if this is mentioned elsewhere, but I did not see it. The stone generated in-world by this mod, both the tiny ones used as ground covering and the actual full blocks, seem to have no hardness set and can be broken with the players hand in one quick mouse click. I am using quite a few mods so it is possible that this is an issue on my end, but I was wondering if this is already known?

**Comment by jonathantai9** [comment]
I'll look into it. The smaller stones as groundcover are supposed to break instantly, though that will change as well.

**Comment by ate0ate** [comment]
Okay, that sounds great. I thank you for looking into it. The ground cover does make sense since it is mostly small pebbles and such, but the stone blocks themselves were somewhat bothersome. Especially when you unintentionally tear barehanded through a patch of it that you meant to harvest lol. Beautiful mod btw. Really livens the world up.

**Comment by mc-jt9** [comment]
Fixed in v1.5.0. Thanks for your feedback!

**Comment by ate0ate** [comment]
Works flawlessly. Thank you so much for the update. And a quick one too!
