### ISSUE TITLE
MC crashes at startup if I disable biomes

### ISSUE THREAD

**Issue by Zergmazter** [mc-jt9/ProjectVibrantJourneys#42]
MC crashes at startup if I disable biomes. Go in the config, under "Master", and set "Biomes: Enable Biomes" to false, in order to reproduce this bug. It also happens when I set to false any of the biomes individually.

**Crash Logs**
https://paste.dimdev.org/lunojucacu.mccrash

**Comment by jonathantai9** [comment]
Crash log shows you're using version 1.5.0. Update to 1.5.1, it should be fixed.

**Comment by mc-jt9** [comment]
Update the mod to the newest version, it should fix the bug,
