### ISSUE TITLE
Disable (fire)flies in snow/ice biomes

### ISSUE THREAD

**Issue by EvertX** [mc-jt9/ProjectVibrantJourneys#43]
It just doesn't feel right having flies in icy/snowy biomes. Could you disable those? Or (if this is possible) change their spawnrate depending om biome temperature. But that might be a bit too involved?

**Comment by mc-jt9** [comment]
Sounds like a good idea. This is done easily, since biomes are tagged with different types. I could just disable fireflies for biomes with the snowy or icy type.

**Comment by mc-jt9** [comment]
Added in 1.6.0
