### ISSUE TITLE
Dimension Blacklist

### ISSUE THREAD

**Issue by O13SC3N3** [mc-jt9/ProjectVibrantJourneys#45]
Config options to blacklist dimensions like for mods Caverns II and such

**Comment by mc-jt9** [comment]
I'll see what I can do about that.

**Comment by mc-jt9** [comment]
Rocks and other groundcover don't drop itself when destroyed, and they're not supposed to drop when the block underneath is removed, that may be a bug. You have to sneak and right-click it to for it to drop. I don't remember why I chose it to drop that way, but it will probably change.

**Comment by mc-jt9** [comment]
Added in 1.6.0 - not tested though
