### ISSUE TITLE
Minor tree generation issues in 1.6.0

### ISSUE THREAD

**Issue by ate0ate** [mc-jt9/ProjectVibrantJourneys#48]
I am quite enjoying the update and things are looking very nice, but I have noticed some issues with certain trees. Mainly the new jacaranda, Cottonwood, and the new Cherry. It seems that they are almost always generating leaves past the log/leaf ratio limit so leaves are always decaying leaving the trees looking rather patchy. I've encountered quite a few trees three or four very lengthy branches shooting out in a "T" or "+" shape resulting in the leaves between branches decaying extensively.

Its easiest to look at the screenshots here to see what I am referring to...
https://imgur.com/a/V3OzEeo

As an off topic aside, the mod is really looking quite nice at this point. I really like some of the more subtle additions. The beaches particularly look amazing with the beach grass and sea oats from this as well as the BoP sea oats. Very nice touch:)

**Comment by mc-jt9** [comment]
I'll try to fix that issue. I've got a few things in mind for the next update which will mostly be those little things that make the world look nice.

**Comment by ate0ate** [comment]
Please, take your time. I just wanted to be sure you were aware of that small tree issue. Absolutely excellent mod you have here. The attention to detail is quite refreshing. I also look forward to the lighting getting its own little mod now. If the standard of quality is anything like in PVJ here it will surely impress. Lighting is rather lacking in minecraft so anything other than torches is always a welcomed addition lol.

**Comment by mc-jt9** [comment]
Thank you! The lighting blocks will be released under a mod called Illumina, and the chimneys will be released with fireplaces under a mod called Home Is Where The Hearth Is.

**Comment by mc-jt9** [comment]
Mostly fixed in 1.6.3
