### ISSUE TITLE
IllegalStateException:not building!

### ISSUE THREAD

**Issue by viceroy369** [mc-jt9/ProjectVibrantJourneys#49]
**Describe the bug**
Been getting this bug in my mod pack during terrain gen: other than that beautiful mod!

**Crash Logs**
https://paste.dimdev.org/toyowupacu.mccrash

**USE https://pastebin.com/** FOR CRASH LOGS PLEASE

**Comment by mc-jt9** [comment]
Looks like a client-sided issue with rendering chunks. This mod doesn't touch any of that stuff - could you check to make sure it's this mod?

**Comment by ate0ate** [comment]
Looking at the crash log I see that Animated Chunks is being used. I would suggest starting with that mod if you plan on trying to narrow down issues/conflicts. Just a suggestion.

**Comment by mc-jt9** [comment]
If I remember correctly this was fixed - closing the issue.
