### ISSUE TITLE
SUGGESTION: Dungeon Changes

### ISSUE THREAD

**Issue by AnonTheMouse** [mc-jt9/ProjectVibrantJourneys#5]
Vanilla dungeons are a cobblestone box with a spawner. With the addition of things like fallen logs and groundcover to make the surface look better, that seems even more jarring. It would be nice to have a few things spawn in dungeons to make them look more varied. For instance, groundcover bones on the floor of dungeons, simple pillars (single block pillar with a few stair accents) that can appear whole or broken along the edge of the room, wall niches (made with stairs), skulls placed on the ground or on simple block "shelves", or other similarly simple decorations. Varying the block types, so that some dungeons show up with your cobblestone bricks would also help.

It would also be good to see dungeons with spawners for your mobs, but my main point is that I'd love to see variation, where no two spawner boxes look alike.

**Comment by mc-jt9** [comment]
Huh, I never thought my mobs being in dungeon spawners. The whole bones thing on the floor is a great idea, I'll see how I can implement your suggestions.

**Comment by mc-jt9** [comment]
Some of this has been implemented in v1.1.4, except the more complicated things. Might get around to doing it in a future update. Will close this for now
