### ISSUE TITLE
Bring back Baobab Fields! + some others

### ISSUE THREAD

**Issue by Graywaren** [mc-jt9/ProjectVibrantJourneys#50]
1.6 seems pretty neat and I really like some of the changes, but Baobab fields were my absolute favorite biome. They're quite literally the only biome of VJ that I kept spawning in my game where I use dynamic trees. (If VJ had compat for that I'd also keep redwoods at least if not all.) I was planning to spawn african type animals in it for the modpack I was creating. I really adore it and am considering avoiding upgrading just to keep it, but I also really want the fixed spawn rates. (Were spiders and snails fixed?) Is there any way that I can add it back in simply for my own game with 1.6?

Some other features I'd really like to see:
Ravens/crows added especially since you're adding scarecrows. I think it'd be neat to have them attracted to them rather than repelled though. 

The ability to black/whitelist specific mobs from certain biomes. Such as preventing the spider from spawning in the snow. It's adorable, but unrealistic. 

The ability to mute the goons

**Comment by mc-jt9** [comment]
The baobab fields caused a lot of cascading world generation lag which is why it was removed. I can add at back in as a config option, off by default. I've been considering birds, but not sure how to do them yet (I'm not good at modelling/animation). I also meant to remove critters from snow biomes, just forgot to do it. Also will consider the thing with goons lol

**Comment by Graywaren** [comment]
Ah, the lag, yea. I'm really sorry to hear that about the fields. Maybe there would be a way to fix it or make a new biome of them? (I'm not sure what exactly cascading worldgen lag is) they really are my favorites. A config option would be a very welcome option at least so i can see how much it is effecting anything and possible keep them. 

Maybe you could team up with better animals plus or exotic birds modders for animal models and such? EB does wonderful birds, but they don't have crows or ravens either. Eventually I would love to get into making my own models, but as I'm new to the whole mod thing, it's gonna be a while til I get there haha. 

Keep up the good work!

**Comment by Graywaren** [comment]
Oh! Also, would really like to see the density part of the config sorted into sections to make it easier to find all your tree types etc.

**Comment by mc-jt9** [comment]
Yeah, the config is pretty messy. I think I'll clean it up soon. Also, I didn't change the behavior of cattails. They should still be placeable? I hope I didn't accidentally break them.

**Comment by Graywaren** [comment]
Oops! My bad. I was confused by the line about them in the changelog and when I first tested it I must have been accidentally trying to plant them in a block that wasn't adjacent to water. I just tested it again and they are working just fine. Sorry about that!

**Comment by mc-jt9** [comment]
I've just released 1.6.1 that has baobab fields as an option in the config.

**Comment by mc-jt9** [comment]
Bugs shouldn't spawn in snow biomes anymore - closing this issue.
