### ISSUE TITLE
Spawn Rates & Places

### ISSUE THREAD

**Issue by Graywaren** [mc-jt9/ProjectVibrantJourneys#51]
I'm not really sure if this is a bug report or feature request, but I'm working on integrating this into a modpack I'm making for a me and a friend to play and have noticed that Mushrooms spawn on tree tops. I really don't think they should be spawning in full light on the tops of trees. I've seen this in every world I've generated with VJ. I've verified this happens with no other mods installed, so it doesn't seem to be an interaction. I have Mc 1.12.2, Forge b2805, & VJ 1.6.

Also the spawn rate on spiders and snails is pretty intense. They're everywhere. I adore the them, but I end up having to turn their spawn down to something around 1-3 and I still get so many. (I suspect this is the same with flies, but I turn those off.) They also spawn in snow. I also notice that they spawn in plains and woodlands a lot more than swamps or savannahs etc and in the case of spiders they're supposed to spawn everywhere, so it's hard to get it so that I can have a smattering of spiders across all biomes. (Hence my request for biome white/black list). I really do love the little buggers, so would love to more easily be able to have them about. (Taming them would be great! tiny spider pet!)

And, I'm not sure if this is something your mod can control, but the map icon used for the spiders in Voxel map is the same icon as is used for full size hostile spiders. I would love having a smaller icon to differentiate between them.

**Comment by mc-jt9** [comment]
Oh yeah, I see the mushrooms a lot when I test features. I can tweak the spawn to not consider leaves.  I'll also try to work on the spider/snail stuff. I'm not sure about the Voxel map stuff, I'm not sure how they handle the icon sizes or if I have any control over that. I personally use JourneyMap which doesn't differentiate between mobs so it hasn't been an issue for me.

**Comment by Graywaren** [comment]
Yea, I think not considering leaves would fix the spawning on top of trees thing. And yea, I am still researching how the heck voxel icons work, but figured I'd ask in case icons are a thing that's usual with mods. Thanks for the info!

**Comment by mc-jt9** [comment]
In 1.6.1, I've lowered the spawn rates in the config by a significant amount. You'll need to delete your config and let the game load a new one for the effects to take place. Please let me know if there are still problems with spawn rates (and sorry the update took so long)
