### ISSUE TITLE
Watcher crash, tries to cast to a Guardian

### ISSUE THREAD

**Issue by Tokeli** [mc-jt9/ProjectVibrantJourneys#52]
MC 1.12.2
Vibrant Journeys 1.12.2-1.6.0
Forge 1.12.2-14.23.5.2814
**Describe the bug**
Random crash in the end when a Watcher is around?!

**Crash Logs**
https://paste.dimdev.org/desumoyame.mccrash

**Comment by mc-jt9** [comment]
uh oh looks like i messed up somewhere, sorry

**Comment by mc-jt9** [comment]
I can't seem to find any issue in the code for this, and I can't replicate the crash either.

**Comment by Chriswow11** [comment]
I also got this issue in a brand new world, but I have many more mods

https://paste.dimdev.org/hovegarika.mccrash

**Comment by mc-jt9** [comment]
For some reason I have been unable to replicate this crash - that's weird. I'll look into it a little more.

**Comment by mc-jt9** [comment]
Fixed in 1.6.2
