### ISSUE TITLE
Stalactites spawn on unnatural blocks.

### ISSUE THREAD

**Issue by Tokeli** [mc-jt9/ProjectVibrantJourneys#53]
MC 1.12.2
Vibrant Journeys 1.12.2-1.6.0
Forge 1.12.2-14.23.5.2814
**Describe the bug**
I'm not sure if this is a true bug or intended behavior, but-

While testing out a modpack with Vibrant Journeys and Lost Cities, the latter mod made it easy to see that stalactites don't respect manmade blocks. Stone stalactites frequently spawn on stone brick ceilings, as will ice stalactites. It's not exactly an issue but it's incredibly weird looking when it's not a natural structure.

**Comment by mc-jt9** [comment]
Because it checks for anything of the stone material when generating. This makes it compatible with all mods that add stones. I'll hard-code in the blocks to fix this.

**Comment by mc-jt9** [comment]
Should be fixed in 1.6.1
