### ISSUE TITLE
[Feature Requests] Serene Seasons Support

### ISSUE THREAD

**Issue by dannydjdk** [mc-jt9/ProjectVibrantJourneys#55]
I would love to see support for the Serene Seasons mod when spawning flies and other critters. It's great that they now don't spawn in snowy biomes, but they do spawn during cold winters in temperate biomes. I would love to see and hear flies just in warmer seasons.
Some mods, such as Rustic, will only allow their plants to grow during warmer seasons, so I suspect it's possible to get the current temperature.
Thank you!

**Comment by mc-jt9** [comment]
I'll take a look at it

**Comment by mc-jt9** [comment]
Bugs shouldn't spawn during the winter season now.
