### ISSUE TITLE
No Squid Spawns

### ISSUE THREAD

**Issue by dannydjdk** [mc-jt9/ProjectVibrantJourneys#56]
Since 1.6.0, no squids spawn in the oceans or otherwise. I've tried disabling the feature to restrict squids to just spawn in oceans. That did not help. Rolling back to 1.5.2 does fix the problem, but then there are no ducks, coyotes or starfish. :(

I am using this pack: https://minecraft.curseforge.com/projects/real-tech
The pack still has 1.5.2, but as soon as this issue is resolved, I'll be pushing an update with 1.6.0. 

Forge version is 14.23.5.2768.

Let me know if there is any other information you'd like from me.
Thanks!

**Comment by ate0ate** [comment]
Hmm, just a total stab in the dark here, but It could be connected to the clam over spawning issue. It may be that the clams are over spawning to the point that squid spawns are basically non-existent. Have you tried disabling clams in the config (setting spawn weight to 0) and seeing if that changes matters?

**Comment by mc-jt9** [comment]
Yeah it has to do with starfish and clam spawns. I'll take a look at it

**Comment by dannydjdk** [comment]
Turning down the starfish and clam spawns in the config to about 1/10th the default did indeed bring the squids back for me.

**Comment by mc-jt9** [comment]
That's a start. This update brought a lot more issues that I didn't catch. Unfortunately I'm also in the middle of exam season so progress will be slow until the middle of March.

**Comment by dannydjdk** [comment]
Dup of #54

**Comment by mc-jt9** [comment]
So I've lowered the spawn rates of all the critters - this means you'll have to delete your config and let the game load a new one. Let me know if there are any more issues with the spawn rates.
