### ISSUE TITLE
Regarding issues in 1.6.0

### ISSUE THREAD

**Issue by mc-jt9** [mc-jt9/ProjectVibrantJourneys#57]
There are several bugs/unintended effects from 1.6.0 that I have yet to fix. I have some exams coming up and other work to do so work on the mod will be slow until mid-March. Please be patient! Any and all feedback and suggestions are always welcome.

**Comment by ate0ate** [comment]
Not a problem at all. Take your time. Clams were the biggest issue for me and they can be worked around for now.

**Comment by dannydjdk** [comment]
You might want to change the release type of 1.6.0 to beta to help prevent any bad first impressions for anyone new to this awesome mod.
