### ISSUE TITLE
Generation from this mod may need heavy optimization

### ISSUE THREAD

**Issue by Sunconure11** [mc-jt9/ProjectVibrantJourneys#58]
This mod was enough to tank the TPS of a server with a small modpack pretty quick.

@cammiepone

**Comment by mc-jt9** [comment]
I will be working on world gen optimization as well as spawn weight stuff. Just keep in mind that it means you'll have to delete your config and let the game load a new one when the next update rolls out.

**Comment by Murdockzor** [comment]
Needs update ASAP. Almost killed my world because I was building near a lake, and found this.
![clams](https://user-images.githubusercontent.com/49251619/55507662-7ef54b80-562e-11e9-9115-e21474ed6205.png)

**Comment by jhth13rteen** [comment]
I am having the exact same issue as well :( Minecraft forge server 1.12.2
STUPID CLAMS!!!

**Comment by CREEATION** [comment]
I'll just leave a few screenshots here regarding worldgen:

![2019-04-05_11 37 19](https://user-images.githubusercontent.com/3277769/55678749-0973ce80-58ff-11e9-8d15-0cde034c9207.png)
![2019-04-05_11 44 23](https://user-images.githubusercontent.com/3277769/55678752-14c6fa00-58ff-11e9-9328-8626245eda1c.png)
![2019-04-05_11 48 09](https://user-images.githubusercontent.com/3277769/55678753-18f31780-58ff-11e9-8c52-0c6bf7a813d1.png)
![2019-04-05_12 04 40](https://user-images.githubusercontent.com/3277769/55678755-1e506200-58ff-11e9-8855-61a173903b61.png)
![2019-04-05_20 22 25](https://user-images.githubusercontent.com/3277769/55678758-2dcfab00-58ff-11e9-83f1-d2ccdfc244aa.png)
![2019-04-05_20 48 12](https://user-images.githubusercontent.com/3277769/55678761-345e2280-58ff-11e9-9d51-544d3137005d.png)
![2019-04-07_05 07 13](https://user-images.githubusercontent.com/3277769/55678765-417b1180-58ff-11e9-9725-9f1d4c617cb2.png)
(this one is basalt underwater, but not really on the ground...)
![2019-04-07_06 27 15](https://user-images.githubusercontent.com/3277769/55678766-4b047980-58ff-11e9-86ec-25331b70ccd2.png)

**Comment by mc-jt9** [comment]
Rewrote a bunch of stuff in 1.6.2
