### ISSUE TITLE
How to fix the black texture on slabs

### ISSUE THREAD

**Issue by akomae** [mc-jt9/ProjectVibrantJourneys#59]
is there a way to fix this?
![image](https://user-images.githubusercontent.com/48612547/54471058-382bd880-4789-11e9-802a-4271bf35d118.png)

**Comment by ate0ate** [comment]
I don't think there is a fix for this yet, but I have seen other mods have this issue and successfully resolve it. I have a similar lighting issue with the cobble brick stairs.

**Comment by mc-jt9** [comment]
Fixed in 1.6.2
