### ISSUE TITLE
SUGGESTION: Lost Cities Compatibility

### ISSUE THREAD

**Issue by Deightine** [mc-jt9/ProjectVibrantJourneys#6]
Vibrant has been pretty awesome to mess about with. Kudos on the hard work so far and I'm looking forward to seeing your new features as they drop. Now on to my request--

**Issue:** [Lost Cities](https://minecraft.curseforge.com/projects/the-lost-cities) turns most of the world environment into abandoned structures. Your mod turns out to have a really awesome side-effect of planting [more material on building rooftops](https://imgur.com/a/HGuvcc4), on the floors of buildings, etc. This was unexpected and delightful. But sometimes it also drops a felled tree _inside_ a building. 

**Request:** Currently Lost Cities applies its world generation in 'spheres' with chunks knowing they're a city tile. If possible, it would be great if we could have a section of the PVJ config that tweaks the drop rates specifically inside these city tiles.

This would at the least curb the number of logs spawning inside buildings or limit all of the added clutter to bones or appropriate rock types, for example. It would be nice if they could be allowed on the 'street' tiles, but I think that'd be a lot more work to integrate.

I would suggest that when the logs are dropped the routine runs a check to see if there is open sky above, if sun could reach that spot for a tree to have grown there. That would both allow them on the external tiles and prevent them inside buildings, caves, etc, that might spawn in some generators. Only concern that comes to mind is it would limit how many fell beneath existing canopy in some biomes.

**Sidenote:** I added your Ghosts and Shades to the haunts in [Lost Souls](https://minecraft.curseforge.com/projects/lost-souls) (mob integration for Lost Cities) and they have _great_ synergy. Padding the spawn rate out with Ghosts has made it less immediately lethal to enter a building, but creates a good opportunity to 'anger' the haunted building to turn the mobs against the player when they're deep inside. Another added bonus for my pack which is post-apocalyptic.

**Comment by mc-jt9** [comment]
Just added a simple check to see if lostcities is installed and disable fallen trees
This will be in the v1.1.1 update, coming out soon.

**Comment by Deightine** [comment]
That's unfortunate as they're very nice outside the cities themselves, but I can respect wanting a quicker fix. Thanks for following up on my suggestion. :)

**Comment by mc-jt9** [comment]
Hmm, might be better if I checked if there is open sky, ignoring leaf blocks. I'll try that.
