### ISSUE TITLE
Crash on Banshee entity?

### ISSUE THREAD

**Issue by ketpain** [mc-jt9/ProjectVibrantJourneys#61]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 3/19/19 8:07 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.monster.EntityMob
	at vibrantjourneys.entities.monster.EntityBanshee.func_70652_k(EntityBanshee.java:89)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at vibrantjourneys.entities.monster.EntityBanshee.func_70636_d(EntityBanshee.java:83)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at vibrantjourneys.entities.monster.EntityBanshee.func_70652_k(EntityBanshee.java:89)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at vibrantjourneys.entities.monster.EntityBanshee.func_70636_d(EntityBanshee.java:83)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: pvj:pvj_banshee (vibrantjourneys.entities.monster.EntityBanshee)
	Entity ID: 389
	Entity Name: Banshee
	Entity's Exact location: -1973.94, 68.00, 1175.03
	Entity's Block location: World: (-1974,68,1175), Chunk: (at 10,4,7 in -124,73; contains blocks -1984,0,1168 to -1969,255,1183), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,0,1024 to -1537,255,1535)
	Entity's Momentum: -0.02, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['KeT_PaiN'/223, l='world', x=-1974.91, y=68.00, z=1175.70]]
	Chunk stats: ServerChunkCache: 934 Drop: 0
	Level seed: -7415846341451160083
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (495,74,427), Chunk: (at 15,4,11 in 30,26; contains blocks 480,0,416 to 495,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 353616 game time, 379336 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 13564 (now: false), thunder time: 20884 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3851829864 bytes (3673 MB) / 6039797760 bytes (5760 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -Xms2048m -Xmx8192m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 2, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 112 mods loaded, 112 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                  | Source                                             | Signature                                |
	|:------ |:------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                       | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2814-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2814             | forge-1.12.2-14.23.5.2814-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore               | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA | actuallyadditions         | 1.12.2-r146              | ActuallyAdditions-1.12.2-r146.jar                  | None                                     |
	| LCHIJA | aiimprovements            | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
	| LCHIJA | biomesoplenty             | 7.0.1.2419               | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar      | None                                     |
	| LCHIJA | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                  | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
	| LCHIJA | craftstudioapi            | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | harvestcraft              | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                    | None                                     |
	| LCHIJA | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| LCHIJA | animania                  | 1.6.2                    | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | applecore                 | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | aroma1997core             | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup               | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery       | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | bottledmilk               | 1.0.0                    | BottledMilk-1.12-1.1.0.jar                         | None                                     |
	| LCHIJA | buildcraftlib             | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftcore            | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftbuilders        | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcrafttransport       | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftsilicon         | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | theoneprobe               | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LCHIJA | buildcraftcompat          | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftenergy          | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftfactory         | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | buildcraftrobotics        | 7.99.22                  | buildcraft-all-7.99.22.jar                         | None                                     |
	| LCHIJA | cavern                    | 2.1.9                    | Cavern_1.12.2-v2.1.9.jar                           | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | champions                 | 1.12.2-1.0.6             | champions-1.12.2-1.0.6.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | chisel                    | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | chiselsandbits            | 14.30                    | chiselsandbits-14.30.jar                           | None                                     |
	| LCHIJA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhworld                 | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | mantle                    | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| LCHIJA | tconstruct                | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| LCHIJA | conarm                    | 1.2.3                    | conarm-1.12.2-1.2.3.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cookingforblockheads      | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar             | None                                     |
	| LCHIJA | customnpcs                | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
	| LCHIJA | props                     | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                         | None                                     |
	| LCHIJA | dldungeonsjbg             | 1.12.3                   | DoomlikeDungeons-1.12.3-MC1.12.2.jar               | None                                     |
	| LCHIJA | dungeontactics            | DT-0.15.8                | DungeonTactics-1.12.2-0.15.8.jar                   | None                                     |
	| LCHIJA | extrautils2               | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | familiarfauna             | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
	| LCHIJA | foamfix                   | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                          | None                                     |
	| LCHIJA | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| LCHIJA | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| LCHIJA | ftblib                    | 5.4.1.88                 | FTBLib-5.4.1.88.jar                                | None                                     |
	| LCHIJA | ftbutilities              | 5.4.0.86                 | FTBUtilities-5.4.0.86.jar                          | None                                     |
	| LCHIJA | ic2                       | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks             | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LCHIJA | itemfilters               | 1.0.1.8                  | ItemFilters-1.0.1.8.jar                            | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LCHIJA | jee                       | 1.0.6                    | JustEnoughEnergistics-1.12.2-1.0.6.jar             | None                                     |
	| LCHIJA | levelup2                  | ${version}               | Level+Up!+2-1.1.22-1.12.jar                        | None                                     |
	| LCHIJA | lex                       | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                             | None                                     |
	| LCHIJA | mcjtylib_ng               | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                            | None                                     |
	| LCHIJA | mcmultipart               | 2.5.3                    | MCMultiPart-2.5.3.jar                              | None                                     |
	| LCHIJA | millenaire                | Millénaire 7.1.3         | millenaire-1.12.2-7.1.3.jar                        | None                                     |
	| LCHIJA | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
	| LCHIJA | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
	| LCHIJA | multimob                  | 1.0.5                    | multimob-1.0.5.jar                                 | None                                     |
	| LCHIJA | netherendingores          | 1.12.2-1.3               | Netherending-Ores-1.12.2-1.3.jar                   | None                                     |
	| LCHIJA | nex                       | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                          | None                                     |
	| LCHIJA | nmsot                     | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar            | None                                     |
	| LCHIJA | recipehandler             | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJA | oreexcavation             | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
	| LCHIJA | simplerecipes             | 1.12.2c                  | Pam's+Simple+Recipes+1.12.2c.jar                   | None                                     |
	| LCHIJA | primitivemobs             | 1.2.3a                   | primitivemobs-1.2.3a.jar                           | None                                     |
	| LCHIJA | projecte                  | 1.12.2-PE1.4.0           | ProjectE-1.12.2-PE1.4.0.jar                        | None                                     |
	| LCHIJA | projecteintegration       | 1.12.2                   | ProjectEIntegration-1.12.2-1.5.0.jar               | None                                     |
	| LCHIJA | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
	| LCHIJA | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar              | None                                     |
	| LCHIJA | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| LCHIJA | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| LCHIJA | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar         | None                                     |
	| LCHIJA | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar            | None                                     |
	| LCHIJA | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| LCHIJA | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| LCHIJA | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| LCHIJA | pvj                       | 1.6.0                    | ProjectVibrantJourneys-1.12.2-1.6.0.jar            | None                                     |
	| LCHIJA | quickleafdecay            | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                  | None                                     |
	| LCHIJA | railcraft                 | 12.0.0-beta-5            | railcraft-12.0.0-beta-5.jar                        | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | reborncore                | 3.13.6.424               | RebornCore-1.12.2-3.13.6.424-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | refinedstorage            | 1.6.12                   | refinedstorage-1.6.12.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | additionalstructures      | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar   | None                                     |
	| LCHIJA | roguelike                 | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA | silentlib                 | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                    | None                                     |
	| LCHIJA | scalinghealth             | 1.3.33                   | ScalingHealth-1.12.2-1.3.33+135.jar                | None                                     |
	| LCHIJA | stevescarts               | 2.4.29.132               | StevesCarts-1.12.2-2.4.29.132.jar                  | None                                     |
	| LCHIJA | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHIJA | thermalfoundation         | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion          | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalcultivation        | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics           | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalinnovation         | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | tombmanygraves            | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                      | None                                     |
	| LCHIJA | topaddons                 | 1.12.2-1.10.1            | topaddons-1.12.2-1.10.1.jar                        | None                                     |
	| LCHIJA | immersiveengineering      | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | structurize               | 1.12.2-0.10.63-ALPHA     | structurize-1.12.2-0.10.63-ALPHA.jar               | None                                     |
	| LCHIJA | minecolonies              | 1.12.2-0.10.202-RELEASE  | minecolonies-1.12.2-0.10.202-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.6.424
		Runtime Debofucsation 1
	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['KeT_PaiN'/223, l='world', x=-1974.91, y=68.00, z=1175.70]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mc-jt9** [comment]
Sorry about that. I will take a look at it. The temporary fix would be to set the banshee spawn weight to 0 in the config until it is fixed.

**Comment by ketpain** [comment]
Honestly no worries. I had to get rid of the mod entirely because even though I set the banshee weight to 0, it'd still load up the entity, therefore crashing my world lol

(Luckily changing the config then putting the mod back in fixed the problem, and thank god the tree's were still where they were supposed to be. :)

Also. Thanks for the quick reply. Very impressed, as I like this mod.

**Comment by mc-jt9** [comment]
No problem! It's spring break for me right now so I'm going to be working on the bugs and hopefully push out a solid bug-fix update next week.

**Comment by ketpain** [comment]
Good to hear. I wish I could do what ya'll do. I'm jealous lol. I'll be keeping an eye out for your bug fixes!

**Comment by mc-jt9** [comment]
Fixed in 1.6.1

**Comment by ketpain** [comment]
Appreciate the update ! :) Hope you're enjoying your break !!
