### ISSUE TITLE
Crash on Banshee (Roguelike Adventures and Dungeons)

### ISSUE THREAD

**Issue by Flimsy-Fox** [mc-jt9/ProjectVibrantJourneys#62]
My friend was playing on the "Roguelike Adventures and Dungeons!" when he found a chest to loot inside a dungeon. After he looted the chest, he looked to the left and found a Banshee. And BAM! Crash.

I assume this either has something to do with how the Banshees are rendered or some incompatibility with other mods. We loaded the world again and it crashed as long as the Banshee was still there. As expected, after we killed the Banshee the crashes no longer occurred.
This is a related post (I couldn't figure out how to mark this in the title; I'm a noob to this site :P):
 #61 
Here is the crash log:
https://paste.dimdev.org/helukukodi.mccrash

**Comment by mc-jt9** [comment]
Yeah it was the result of lazy copy-paste stuff that I didn't double check. It will be fixed in the next update.

**Comment by mc-jt9** [comment]
Fixed in 1.6.1
