### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by djruss7** [mc-jt9/ProjectVibrantJourneys#64]
I've been playing "Roguelike Adventures Dungeons!" for a couple of days and now every time I load my world the game crashes as soon as it opens. Sometimes It loads me in the world for 1 second, but never longer than that. Is there anything I can do to fix this?

Here's the report: https://paste.dimdev.org/otureqipav.mccrash

Thanks

**Comment by mc-jt9** [comment]
There's a fix coming soon.

**Comment by mc-jt9** [comment]
Yep fixed in 1.6.1
