### ISSUE TITLE
Stereo Audio Issue

### ISSUE THREAD

**Issue by TechnoMysterio** [mc-jt9/ProjectVibrantJourneys#65]
The audio files for this mod present a minor issue in how Minecraft processes them. I've done sound design for mods in the past and it took me a while to realise this myself, so I'll give you a quick rundown.

A lot of the audio files in this mod are in stereo. Stereo sounds in Minecraft always play in both ears, even if the source of the sound is off to the side, or at a distance. This means that sounds like this can be confusing to players, since if a monster or some such is approaching them from the side or from behind them then the audio doesn't show this, instead making it seem like the monster is right in front of them. This can also make such audio a little more annoying, due to this difference between what you hear and what you see.

Stereo sounds, however, are fine for music, ambience, or larger events that happen around the player or that need more impact. The Wither summoning sound from vanilla is stereo, for example.

To solve this issue, I'd recommend that you go over the audio files for the mod and convert any of the sounds that need to come from a position in the world (so I'd say all the sounds since it's pretty much just mob audio) to mono, using Audacity or something. This would help make the sounds work much better in-game, and would also cut down on filesizes a little.

Also the sound of someone burping would be better in mono, since currently it makes the Goon sound like it's always belching right in my face. This makes me feel uncomfortable... also somewhat violated.

**Comment by mc-jt9** [comment]
Hi, thanks for the suggestion. I have a lot of reworks/redesigns/optimization to do and this sounds (no pun intended) like something I should work on.
Also, after many hours playing the Binding of Isaac, the goon sounds don't really have any effect on me, although other people have told me it is disgusting.

**Comment by mc-jt9** [comment]
Fixed in 1.6.3
