### ISSUE TITLE
Watcher Crash in the End

### ISSUE THREAD

**Issue by katubug** [mc-jt9/ProjectVibrantJourneys#66]
**Describe the bug**
I'm not sure what caused the crash, but all of my players and I got the same report at the same time upon entering The End. We're in version 1.6.1. Please let me know if you have any questions!

**Crash Logs**
https://paste.dimdev.org/omaqafolen.mccrash

**Comment by mc-jt9** [comment]
I think I fixed it. I can't seem to replicate the crash, but I found what could be causing it. I'm working on other small fixes right now as well and I'll try to push out an update tomorrow.

**Comment by katubug** [comment]
Cool, thank you!

**Comment by mc-jt9** [comment]
Fixed in 1.6.2 - the update also includes several changes to world generation and you'll need to let delete the mod's config to let the game generate an updated one.
