### ISSUE TITLE
Snails now spawn indoors?

### ISSUE THREAD

**Issue by katubug** [mc-jt9/ProjectVibrantJourneys#67]
**Describe the bug**
Spawning of small creatures does seem to be improved, but they might not be adhering to normal spawn rules? Not sure what those are tbh. We've just got a big ol' bunch of snails in our base.

**Comment by mc-jt9** [comment]
Ah, right. I fixed the spawn rates by switching the bugs to the ambient creature type instead of animal type. I forgot that only animals check to spawn only on grass and not these bugs. I'll fix that tonight.

**Comment by katubug** [comment]
Thanks!

**Comment by mc-jt9** [comment]
Just released 1.6.3. They should only spawn on grass now.
