### ISSUE TITLE
Cattails can't be planted on UBC sand

### ISSUE THREAD

**Issue by WenXin20** [mc-jt9/ProjectVibrantJourneys#69]
#### Issue Description:

Cattails from this mod can't be planted on sand from Underground Biomes, but the small cactus can. The mod replaces Minecraft sand during world generation with different types of sand. I often find the items dropped onto the ground after world generation. 

#### Steps to reproduce:

1. Create a world
2. Find a desert
3. Try to plant cactus/cattails on it.
4. Also find items dropped on the ground where a plant should be.

#### Additional Information:

Also reported here: Aang23/UndergroundBiomesConstructs#100

____
#### Affected Versions:

- Project: Vibrant Journeys: v1.6.3
- Underground Biomes: v1.3.4
- Minecraft: v1.12.2
- Forge: v14.23.5.2838

**Comment by mc-jt9** [comment]
I'll find a fix.

**Comment by Aang23** [comment]
if you need help, or anything done on my side, I'm here to help. If you need UBC in your workspace, UBC is in a maven repo.

**Comment by mc-jt9** [comment]
Should be fixed in the 1.6.4 update
