### ISSUE TITLE
Crash (forge-14.23.4.2750)

### ISSUE THREAD

**Issue by Waynekosimoto** [mc-jt9/ProjectVibrantJourneys#7]
**Describe the bug**
Crashed on start. It's a big modpack, not sure what happened.

**Crash Logs**
https://hastebin.com/zitiquwehu.sql

**Comment by mc-jt9** [comment]
Sorry, the crash originated from poor java practice. Fixed it in the latest update (v1.1.1).
It was basically trying to add BoP biomes to a list even if the biome was deactivated.
