### ISSUE TITLE
Dimension Blacklist

### ISSUE THREAD

**Issue by ToxicVenom3** [mc-jt9/ProjectVibrantJourneys#71]
**Describe the bug**
The game crashes during world creation whenever I add a dimension to the blacklist of the config file.

I can get you a full crash log later if you want but these looked like the main cause of the crash.

**Crash Logs**
java.lang.NullPonterException
  at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:171)
  at vibrantjournies.worldgen.WorldGenFallenLeaves.generate(WorldGenFallenLeaves.java:40)

I've only tried this with multiple mods that add their own dimensions. I only disabled the nether as a test. It doesn't appear to be an issue with any other mods but will try later with just this mod installed to see if i get the same result.

**Comment by mc-jt9** [comment]
Took a look at the code. I forgot to add a null check because it's looking to match a nonexistent dimension with an id.

**Comment by Elwood0** [comment]
Hello, I'm facing the same issue in regards to the blacklist. Whenever I add any dimension, Modded or Vanilla, it crashes the game when generating a new world. Hope this gets addressed soon.

Mods Tested: Aether, Between Lands, & Twilight Forest.

**Comment by mc-jt9** [comment]
Should be fixed now.
