### ISSUE TITLE
Hammer core or Galacticraft incompatability

### ISSUE THREAD

**Issue by SpGilbert** [mc-jt9/ProjectVibrantJourneys#77]
Minecraft version:1.12.2
Galacticraft version: 226
single player
https://paste.dimdev.org/xojowibajo.mccrash this crash report does not have the problem only the mod names. also crashed as well for another reason while removing galacticraft
problem:
Prevents all world gen with project vibrant journeys no crash reports only.log file.
.log file:
A clear and concise description of what the bug is. Include steps to reproduce
not sure this problem started 2-3 weeks ago had both mods beforehand but have been updating one
**Crash Logs**
.log file
https://paste.ubuntu.com/p/cHtygpF4Qz/

**Comment by mc-jt9** [comment]
I'm currently busy with other things right now, but I'll make sure to take a look at this when I get back to modding.

**Comment by mc-jt9** [comment]
Should be fixed now.
