### ISSUE TITLE
Duplicate Stat ID with Youtuber's Lucky Blocks

### ISSUE THREAD

**Issue by WenXin20** [mc-jt9/ProjectVibrantJourneys#8]
**Bug Description:**
Forge v14.23.4.2750-1.12.2
[Youtuber's Lucky Blocks ](https://minecraft.curseforge.com/projects/youtubers-lucky-blocks)v6.1.3-Beta1
Project: Vibrant Journeys v1.1.1

I got a duplicate stat id crash with the Youtuber's Lucky Blocks Mod. Is it possible for this to be fixed?
1. Install the Youtuber's Lucky Blocks  and Project: Vibrant Journeys mods.
3. Luanch Minecraft.

[**Crash Log**](https://pastebin.com/yJQneATn)

**Comment by Sunconure11** [comment]
Can confirm a similar crash, but with mob mash.

https://pastebin.com/VKPMMU5u

**Comment by mc-jt9** [comment]
Sorry, about that. It's always a good idea to add your mod id to the entity name, but I guess I did not. I'll fix this for the next update, but the mod authors of both of those mods are also at fault.

**Comment by mc-jt9** [comment]
fixed in v1.1.2
