### ISSUE TITLE
Aggressive mobs spawn in mushroom island biome

### ISSUE THREAD

**Issue by P3pp3rF1y** [mc-jt9/ProjectVibrantJourneys#80]
As said in the title aggresssive mobs spawn in mushroom island biome, which I believe should still be considered safe.

I actually feel like this happens by mistake as all overworld biomes are passed into mob spawn registry, so just excluding the "mushroom_island" and "mushroom_island_shore" should do the trick.

**Comment by mc-jt9** [comment]
Should be fixed in the latest update.
