### ISSUE TITLE
Problem, idk what this is but mod loader

### ISSUE THREAD

**Issue by espovispo** [mc-jt9/ProjectVibrantJourneys#89]
I was trying to add various mods to a modpack, but this mod had an error.

Minecraft said this: 

Minecraft failed to start.

the following mods has prevented an issue to minecraft : Project - Vibrant Journeys 

click get link

so this was the link they gave me, I don't know how to read this code, or what the error is, so please help.

https://paste.dimdev.org/acileqidup.mccrash

**Comment by mc-jt9** [comment]
You've reached your id limit, because the game can only assign a limited amount of ids to items. You'll have to remove some mods until you get below the limit.
