### ISSUE TITLE
Some sort of Mod Conflict in 1.15.1

### ISSUE THREAD

**Issue by Camawama** [mc-jt9/ProjectVibrantJourneys#96]
Hey there, my name is Alex and I have been trying to put together this Modpack for me and some friends to play on. Your mod works perfectly fine client-side but when running on a server it crashes and doesn't even load the world (like a few other mods I tried installing. I have put together a ZIP file with the Logs, Crash report (if there is one), and the other mods installed with it. I did this for every mod that caused the server to crash and I am contacting developers of the mods in hopes that it's enough information to diagnose the problems. I love to discover bugs and report them so if you ever need some help my discord is Cama#6274

Forge Version: Forge-30.0.39
Minecraft Version: 1.15.1

Here is the link to the logs and crash report: http://www.mediafire.com/file/zwad5fufypk1s2d/Elementary_Ores.zip/file

**Comment by OrderedChaos-Dev** [comment]
Can you link to the logs/crash report because they should already show all the mods installed and so I don't have to download a 130 mb file

**Comment by Camawama** [comment]
In a bit when I am free once again I will link to the logs and crash report not the mods. Sorry about that. I just thought you might want to make sure it isn't a mod conflict.

**Comment by Camawama** [comment]
[Logs and Crash.zip](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/4079976/Logs.and.Crash.zip)
Sorry that took so long

**Comment by OrderedChaos-Dev** [comment]
Fixed - it was because I misplaced a function that should only be running on the client. The fix will be in the beta release that I will put out soon, which you should wait for because it adds in most of the content from the 1.12 version as well as lots of new stuff.

**Comment by Camawama** [comment]
Thank you!
