### ISSUE TITLE
Server Crash when interacting with certain groundcover blocks [1.15.2][Beta-2.0.0]

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [mc-jt9/ProjectVibrantJourneys#99]
While I was exploring the newest version of this mod on my modded server, I was in a pvj prairie biome and pick blocked a dung block and accidentally right clicked on it, which placed a lantern next to it and immediately afterwards led to this crash.

This crash also happens when trying to place that particular block in the world from my inventory.

Crash Report is below:
[crash-2020-04-28_12.55.25-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/4545612/crash-2020-04-28_12.55.25-server.txt)

**Comment by OrderedChaos-Dev** [comment]
Found the problem, the fix will be included in the next release

**Comment by The-Bernician-Lamb** [comment]
Thanks a lot! Loving this mod! Keep up the great work!
